DBCDK/content-first

src/client/redux/Store.js
Jeg sidder og leger lidt med koden, og tænker om vi skal tilføje support for redux-devtools-extension?
Det er kun en mindre instrumentering af koden, og det er praktisk når man sidder og udvikler/debugger, eller blot dykker ned i koden, som jeg gør nu ;) Redux-devtools-extension er en browser extension hvor man kan se/debugge redux state og actions i browseren. Det kræver, at man eksponerer state'en, som I kan se her i pull-requesten, for at den kan bruges.
=> redux-devtools-extension support

src/client/redux/__tests__/users.test.js, src/client/redux/root.reducer.js, src/client/redux/users.js, src/index.js
Users-delen af state'en tænkes at indeholde alle profil-data, og tanken er, at hver gang man i anden middleware henter data, der refererer til en user, så dispatcher man `REQUEST_USER`.
---
Vi talte for noget tid siden om at refaktorere state, så jeg har det i forbindelse med implementeringen #226, gjort det som det ville være mest naturligt for mig, fremfor helt at matche den eksisterende kodetilgang. Dette er et oplæg til diskussion om hvorledes vi griber redux/state an, - og vil derfor høre hvad i tænker om denne tilgang (ellers skrive jeg det bare om, så det matcher den eksisterende kodestil).
Forskelle fra eksisterende kode:
- reducer, middleware (og eventuelle selectors) ligger sammen, - hvis de var betydeligt mere komplicerede ville jeg splitte dem op i flere filer. Bruger bare …
=> DISCUSSION: users in state

src/client/App.js, src/client/components/belt/BooksBelt.container.js, src/client/components/filter/FilterPage.container.js, src/client/components/general/Link.component.js, src/client/components/list/ListCard.component.js, src/client/components/work/WorkPage.container.js
#310
- filtersiden har fået fast path: /find
- afkoblet fra bånd på forsiden (dropdown er fjernet), så nu er det kun tag-id'er i url query parameter der søges ud fra.
=> Filterside redesign (part 1)

src/client/redux/__tests__/list.reducer.test.js, src/client/redux/list.reducer.js, src/index.js
Løser issue #418 
Bøger som allerede er tilføjet til en visuel el. simpel liste, har ikke en position key på sig. Ændre man en liste til en bogreol vil bøgerne springe rundt på siden, til de får en position key. 
Dette pr sikre at alle bøger på lister får en default random position ved indlæsningen. LIST_LOAD_RESPONSE
=> old list upgrade to bookcase

src/client/redux/middleware.js, src/client/utils/requestLists.js, src/client/utils/requester.js
call fetchBooks, instead of reading directly from `/v1/books`, to make sure we populate bookReducer with metadata incl. cover for all books we have in the frontend, fixes #425
=> call fetchBooks for all loaded books

public/index.html
løser issue #404 
- Polyfill importeres 2 gange, både i index.html (<script>) og i index.js (import). Dette resultere i en "values-er-allerede-defineret" fejl 2. gang polyfill indlæses, og forhindre hele siden i at blive indlæst.
Polyfill er fjernet i index.html.
=> 404 content-first not working in IE11

src/acceptance/1-object_test.js, src/acceptance/v1-stats_test.js, src/integration/v1-object_test.js, src/migrations/20180606100000_objects.js, src/seeds/seed-db.js, src/server/constants.js, src/server/external-v1-object.js, src/server/objectStore.js
Del af GDPR #430.
Flytter objekt-endpointet til at bruge content-first databasen. Henter og migrerer data fra community-servicen når de tilgås, hvis de ikke allerede er flyttet til content-first-databasen.
Coverage går lidt ned, da den nye implementation skygger over dele af den gamle, som så ikke længere bliver testet.
=> Flyt objekt-endpointet til content-first databasen fra community-servicen

src/client/utils/requester.js
I visse tilfælde kaldes fetchTags med en invalid pid, denne kode ignorerer dette i stedet for at grænsefladen brager ned.
Jeg tror at kilden til at invalide pids er rettet, men de kan stadigt ligge i brugerdata.
=> bug workaround.

src/client/components/general/AddToListButton.component.js, src/client/components/list/AddToList.container.js, src/client/components/list/ListCard.component.js, src/client/components/list/ListCreate.container.js, src/client/components/list/ListItem.component.js, src/client/components/list/ListOverviewDropDown.container.js, src/client/components/list/ListPage.container.js, src/client/components/list/Lists.container.js, src/client/components/list/__tests__/AddToList.container.test.js, src/client/components/list/__tests__/ListCreate.test.js, src/client/components/list/__tests__/ListItem.test.js, src/client/components/list/__tests__/Listpage.test.js, src/client/components/list/__tests__/ListsContainer.test.js, src/client/components/list/__tests__/__snapshots__/AddToList.container.test.js.snap, src/client/components/list/__tests__/__snapshots__/ListCreate.test.js.snap, src/client/components/list/__tests__/__snapshots__/Listpage.test.js.snap, src/client/components/list/__tests__/__snapshots__/ListsContainer.test.js.snap, src/client/components/list/templates/SimpleList.component.js, src/client/components/list/templates/__tests__/BookcaseTemplate.test.js, src/client/components/list/templates/__tests__/CircleTemplate.test.js, src/client/components/list/templates/__tests__/__snapshots__/BookcaseTemplate.test.js.snap, src/client/components/list/templates/__tests__/__snapshots__/CircleTemplate.test.js.snap, src/client/components/work/WorkPreview.component.js, src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap, src/client/redux/__tests__/list.reducer.test.js, src/client/redux/interaction.middleware.js, src/client/redux/list.reducer.js, src/client/redux/middleware.js, src/client/utils/requestLists.js
#263 
Fejlen opstod fordi på nogle ældre lister var id og _id ikke ens - og det var lidt forskelligt, hvilken property der blev brugt rundt omkring i koden. Nu bruges kun _id, så forhåbentligt rettes fejlen.
=> use list._id instead of list.id

src/client/components/filter/TagsSuggester.component.js
Backfill limit er nu ændret fra max 6 til 10 - så max resultatet følger de øvrige max resultater i suggesteren.
=> adjustet title backfill limit

src/client/components/work/WorkCard.container.js
Løser DELVIST issue: #628 
Linebreak er kun tilføjet til workCard componenten som bruges på blandt andet forsiden og filtersiden.
=> 628 - added linebreak to description in workCard component

src/client/components/filter/SearchBar.component.js, src/client/components/filter/SelectedFilters.component.js, src/client/components/filter/TagsSuggester.component.js, src/client/components/list/ListOverviewDropDown.container.js
løser issue: #601 
klientfiltrenes sortering med de øvrige tags vil i nogen tilfælde opleves lidt forkerte, da de 2 tagobjekter bare er sat sammen. 
Der oprettes et nyt issue på bedre sortering af søgeresultaterne i suggesteren, for både tags, klient tags, forfatterer og titler.
=> 601 length in suggester

src/server/external-server.js, tools/put-data.js
related to #757 
howru giver en checksum af taksonomi tilbage.
På inject-tidspunktet bruges checksum til at finde ud af om metakompas og content-first er i sync
=> validate checksum of taxonomy before injecting data

src/client/components/comments/CommentInput.component.js, src/client/components/comments/__tests__/__snapshots__/CommentContainer.test.js.snap, src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
Assure that the save button (Kommentér) is not hidden when blurring, and when there is content in the input field.
Furthermore fix a bug, where it was possible to leave the input field with the tabulator key, and still the save button was visible (for the Chrome browser) - even if the input field was empty.
=> 836 dont hide save button slf

src/client/components/work/FullTextReview.component.js, src/client/components/work/ResumeReview.component.js, src/client/components/work/Review.css, src/client/components/work/__tests__/__snapshots__/FullTextReview.component.test.js.snap, src/client/components/work/__tests__/__snapshots__/ResumeReview.component.test.js.snap, src/client/utils/dateTimeFormat.js
Peter havde følgende kommentarer:
- Første afsnit i lektørudtalelserne skal ikke være med semi-bold, da det giver uhensigtsmæssig visning af ældre lektørudtalelserne, hvor der kun er 1 langt semi-bold afsnit (se fx Erlend Loe - Doppler)
- Datoen for lektørudtalelserne på selve visningen skal anvende forkortelser og altid kunne være på én linie på mobilvisning
- I udfoldet visning (fra startsiden på desktop) er tekststørrelsen på lektørudtalelserne større end resten af indholdet (på den udfoldede visning). Tekststørrelsen på lektørudtalelserne skal derfor gøres mindre så de er samme størrelse. NOTE: det bør overvejes om man skal refaktorere udfoldet visning som komponenten matcher dem på værksiden, hvilket de ikke gør idag.
Formatet for anmeldelser fra Litteratursiden bør revurderes, da de …
=> #629 Rettelser efter test

src/client/redux/order.reducer.js
Det ser ud til, at der er introduceret en fejl under refaktoreringen af order-reduceren. Ved at ordne denne, burde #925 også blive løst.
=> Availability bugfix, fixes #925

src/client/style/components/modal.css
found position:absolute is problematic so made a work around to avoid using it.
=> To fix iPad close button position

src/client/components/hoc/Follow/withFollow.hoc.js
Det skal bruges i forbindelse med list-aggregations til at slå op hvor mange der følger en liste
=> make it possible to look up follows by key

src/client/components/base/Expand/Expand.css, src/client/components/base/T/T.json, src/client/components/belteditor/CreateBelt.component.js, src/client/components/work/WorkPage/WorkPage.container.js, src/client/components/work/WorkPage/WorkPage.css, src/client/components/work/WorkPreview/WorkPreview.component.js, src/client/components/work/WorkPreview/WorkPreview.css, src/client/redux/books.reducer.js
Fixes til CF-1274-appeals:
Rasmus' kommentarer fra tidligere test, som gerne skulle være løst i denne "patch".
Vedr. CF-1274: OK på staging, at klik på "Se hele læseoplevelsen" får panelet til at skøjte over på "Læseoplevelse". Men:
870970-basis:25039505 har tagget "Den 2. verdenskrig" under "Minder om", men ikke i panelet.
870970-basis:21065986 har ingen tags under "Minder om", men flere tags i panelet.
870970-basis:52623723 har hverken tags under "Minder om" eller i panelet, men knappen "Se hele læseoplevelsen" vises alligevel. Panelet skulle måske have en tekst ala "Vi har ikke nogen beskrivelse af bogen".
Der ses ingen forklaring på, hvorfor nogle tags er grønne. Man kan tro, at kun de grønne gælder for bogen.
Hvis der er mange tags i panelet, skal man klikke "Vis mere" efter klik på …
=> CF-1274-appeals (patch)

src/client/redux/roles.reducer.js, src/client/redux/root.reducer.js, src/server/external-v1-initial-state.js, src/server/internal-v1-test.js, src/server/objectStore.js
Man kan nu slå et id på en rolle op ud fra machineName. Data ligger i redux state fra start - også selvom brugeren ikke er logget ind - eller at brugeren ikke har den rolle:
state.roles.contentFirstEditor._id
Kan så bruges til at hente belts ud der tilhører den rolle
=> make roles available in initial-state

e2e/cypress/fixtures/order/canorderawork.mock.json, e2e/cypress/fixtures/order/orderbuttondisabledwhileloadingavailability.mock.json, e2e/cypress/fixtures/order/orderbuttondisabledwhileloadinguser.mock.json, e2e/cypress/integration/order.spec.js, e2e/cypress/util/OpenplatformMock.js
Der var lige nogle cypress tests der fejlede. Jeg har ikke demo'et openplatform-mock-recorder jeg har bikset sammen, så jeg har optaget noget ny mock-data.
Der bliver nu sendt to pid'er i order-requestet, er det fint?
=> update mock data to fix order tests

docker-compose-cypress.yml, docker-compose-dev.yml, src/server/internal-v1-test.js, src/server/objectStore.js
Skal først rulles ud når https://github.com/DBCDK/serviceprovider/pull/1049 er rullet i drift
Husk at opdatere cf-typen så snart denne er i drift - indtil da vil content-first ikke kunne snakke sammen med sp-storage
=> use native _created

src/client/components/hoc/Holding/withHoldings.hoc.js
Det vigtige her er at det der hentes ud med useSelector er så specifikt som muligt. På den måde vil hver holding-state-change ikke medføre at alle komponenter wrapped af withHoldings bliver renderet. Dvs hvis man har 100 komponenter vil der blive lavet ca 100*100 renderinger hvis de hver henter holdings ud én gang. Det kan altså hurtigt løbe løbsk. Vi skal gerne holde den til 100 renderinger.
Derudover er det ikke nødvendigt med shallowEqual - som er meget langsommere end et simpelt "strict equality check", som useSelector bruger som default.
=> only render relevant components wrapped by withHoldings

src/client/components/modals/OrderModal.css
The dropdown at the bottom of the order books sequence can be hidden under the order button on some mobile devices. This assures that all main devices will be able to see the dropdown.
=> initial commit

src/lib/services/recompas-tags.js
Den nye tags recommender forlanger (åbenbart) single quotes og vil ikke acceptere double quotes omkring branch navnet
=> Bugfix: To adapt to new tags recommender
