- doc/endpoints.md
- src/fixtures/blendstrup-havelaagebogen.json
- src/integration/schemas/book-data-out.json
- src/integration/v1-book_test.js
- src/integration/v1-books_test.js
- src/migrations/20170921203056_subject_genre.js
- src/server/books.js
- src/server/books_test.js
- src/server/schemas/book-in.json
Removed unused published_year, published_month, published_day.
Fixes part of #37.
> Added first_edition_year, genre, subject, literary_form to DB.

- package.json
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/general/LineBehindText.component.js
- src/client/components/list/ShortList.container.js
- src/client/components/list/ShortListDropDown.container.js
- src/client/components/list/__tests__/ShortList.container.test.js
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/list/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
- src/client/components/modals/AddToListModal.container.js
- src/client/components/modals/Modal.container.js
- src/client/components/modals/__tests__/AddToListModal.test.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/redux/middleware.js
- src/client/redux/shortlist.reducer.js
- src/client/style/components/shortList.css
- src/client/style/utils/utils.css
- src/setupTests.js
#79 og #85 
- also added enzyme
> Short list page

- package.json
- src/client/components/frontpage/FrontPage.container.js
- src/client/components/general/BookCover.component.js
- src/client/components/general/LineBehindText.component.js
- src/client/components/list/BookSearchSuggester.js
- src/client/components/list/ShortList.container.js
- src/client/components/list/__tests__/ShortList.container.test.js
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/search/__tests__/SearchPage.test.js
- src/client/components/work/OrderButton.component.js
- src/client/components/work/WorkPage.container.js
- src/client/redux/middleware.js
- src/client/redux/order.reducer.js
- src/client/redux/root.reducer.js
- src/index.js
- src/integration/v1-bugfixes_test.js
- src/lib/services/elvis/transformers.js
- src/server/user.js
Mergeable/demoable prototype in progress - currently needs open-platform token supplied via url, to successfully order.
> Order Button

- src/client/components/modals/AddToListModal.container.js
- src/client/components/modals/ShortListMergeModal.container.js
> cleanup: remove show-attribute, fixes #139

- src/lib/services/elvis/community.js
- src/lib/services/elvis/community_test.js
- src/lib/services/elvis/transformers.js
- src/lib/services/hejmdal/login-hejmdal.js
- src/lib/services/hejmdal/login-hejmdal_test.js
- src/lib/services/hejmdal/login-user-info-out.json
- src/server/external-hejmdal.js
- src/server/external-v1-user.js
- src/server/user.js
> pass openplatformToken through the backend, #149

- package-lock.json
- src/fixtures/schemas/user-data-out.json
- src/integration/seed-community.js
- src/integration/v1-bugfixes_test.js
- src/integration/v1-lists_test.js
- src/integration/v1-login_test.js
- src/integration/v1-profiles_test.js
- src/integration/v1-shortlist_test.js
- src/integration/v1-user_test.js
- src/lib/services/elvis/community.js
- src/lib/services/elvis/community_test.js
- src/lib/services/elvis/schemas/connector-profile-in.json
- src/lib/services/elvis/schemas/elvis-profile-data.json
- src/lib/services/elvis/transformers.js
- src/lib/services/hejmdal/login-constants.js
- src/lib/services/hejmdal/login-hejmdal.js
- src/lib/services/hejmdal/login-hejmdal_test.js
- src/lib/services/hejmdal/login-user-info-out.json
- src/server/config.js
- src/server/external-hejmdal.js
- src/server/user.js
> Use Openplatform Id as canonical user Id

- doc/community-service-data-model.md
- doc/endpoints.md
- doc/internal-endpoints.md
- src/fixtures/schemas/public-user-data-out.json
- src/fixtures/schemas/public-user-links-out.json
- src/fixtures/schemas/user-data-out.json
- src/integration/test-commons.js
- src/integration/v1-login_test.js
- src/integration/v1-profiles_test.js
- src/integration/v1-role_test.js
- src/integration/v1-shortlist_test.js
- src/integration/v1-user_test.js
- src/lib/services/elvis/community.js
- src/lib/services/elvis/community_test.js
- src/lib/services/elvis/schemas/connector-profile-in.json
- src/lib/services/elvis/transformers.js
- src/lib/services/elvis/transformers_test.js
- src/server/external-hejmdal.js
- src/server/external-v1-lists.js
- src/server/external-v1-profiles.js
- src/server/external-v1-shortlist.js
- src/server/external-v1-user.js
- src/server/internal-v1-role-add.js
- src/server/internal-v1-role-remove.js
- src/server/internal-v1.js
- src/server/schemas/role-in.json
- src/server/schemas/user-in.json
- src/server/user.js
With a little support for user image
> Issue 131 roles jp

- src/client/components/modals/LoginModal.component.js
- src/client/components/modals/Modal.container.js
- src/client/components/modals/ShortListMergeModal.container.js
- src/client/components/modals/__tests__/LoginModal.test.js
- src/client/components/modals/__tests__/__snapshots__/LoginModal.test.js.snap
- src/client/redux/middleware.js
- src/client/redux/modal.reducer.js
- src/client/style/components/modal.css
- src/client/style/components/shortList.css
> Modal om at brugeren skal logge ind.

- package-lock.json
- package.json
- src/acceptance/v1-image_test.js
- src/seeds/seed-db.js
- src/server/external-server.js
- src/server/external-v1-image.js
Requires user to be logged in (part of #177)
> Public endpoint for posting images

- src/client/components/modals/Modal.component.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
> close modal on background click

- src/client/components/modals/Modal.component.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/style/components/modal.css
#160 
issue 44 er forkert i branch navn
> close modal on background click updated

- src/client/redux/middleware.js
- src/client/redux/order.middleware.js
- src/index.js
- src/server/external-v1-log.js
- src/server/external-v1-openplatform.js
- src/server/external-v1.js
#154 
merge #198 first, to get a sensible diff
> 154 log from client

- src/client/redux/middleware.js
- src/client/redux/order.middleware.js
- src/index.js
- src/server/external-v1-openplatform.js
- src/server/external-v1.js
> 178 work availability order

- src/client/components/general/CheckmarkButton.component.js
- src/client/components/general/CheckmarkConnected.component.js
- src/client/components/general/__tests__/CheckmarkConnected.test.js
- src/client/components/general/__tests__/__snapshots__/CheckmarkConnected.test.js.snap
- src/client/components/work/WorkItem.component.js
- src/client/components/work/WorkItemConnected.component.js
- src/client/components/work/WorkPage.container.js
- src/client/style/components/checkmarkmenu.css
- src/client/style/work.css
> 171 add multibutton mtni

- src/client/components/list/Lists.container.js
- src/client/components/profile/UserProfileForm.component.js
* Change Create profile label to save profile when editing
* Make sure book covers are rendered correctly
related to #173
> Fix minor problems on Profile page.

- src/client/components/top/TopBar.component.js
> Convert profile image to real link

- .travis.yml
- src/client/components/bookcase/Bookcase.component.js
- src/client/components/bookcase/Carousel.component.js
- src/client/components/bookcase/__test__/Bookcase.test.js
- src/client/components/bookcase/__test__/Carousel.test.js
- src/client/components/bookcase/__test__/__snapshots__/Bookcase.test.js.snap
- src/client/components/bookcase/__test__/__snapshots__/Carousel.test.js.snap
- src/client/components/pulse/Pulse.component.js
- src/client/components/pulse/__test__/__snapshots__/Pulse.test.js.snap
- src/client/redux/bookcase.reducer.js
- src/client/redux/books.reducer.js
- src/client/redux/middleware.js
- src/client/redux/root.reducer.js
- src/client/style/components/pulse.css
- src/client/utils/requester.js
> booksreducer added

- src/client/components/list/ListCreate.container.js
- src/client/components/list/__tests__/ListCreate.test.js
- src/client/components/list/__tests__/__snapshots__/ListCreate.test.js.snap
- src/client/style/components/listCreate.css
- src/client/utils/requestLists.js
- src/fixtures/schemas/list-data-out.json
- src/integration/seed-community.js
- src/integration/test-commons.js
- src/integration/v1-lists_test.js
- src/integration/v1-public-lists_test.js
- src/lib/services/elvis/community.js
- src/lib/services/elvis/community_test.js
- src/lib/services/elvis/fixtures/elvis-full-query-for-list-entities-data.json
- src/lib/services/elvis/fixtures/frontend-user-info-out.json
- src/lib/services/elvis/fixtures/transformers-separated-user-info-out.json
- src/lib/services/elvis/schemas/connector-list-in.json
- src/lib/services/elvis/schemas/connector-update-list-in.json
- src/lib/services/elvis/schemas/elvis-entity-query-data.json
- src/lib/services/elvis/schemas/elvis-singleton-entity-query-data.json
- src/lib/services/elvis/transformers.js
- src/lib/services/elvis/transformers_test.js
- src/server/schemas/list-in.json
> Add flags for social and open lists

- src/client/components/general/CheckmarkConnected.component.js
- src/client/components/list/Lists.container.js
- src/client/components/modals/AddToListModal.container.js
- src/client/components/modals/__tests__/AddToListModal.test.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/components/work/WorkItemConnected.component.js
- src/client/components/work/WorkPage.container.js
- src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap
- src/client/redux/__tests__/list.reducer.test.js
- src/client/redux/list.reducer.js
Skyldtes at når state.userReducer.openplatformId er undefined, så tror getLists at man spørger efter alle lister.
> fix bug where not logged in user sees all public lists as its own

- src/client/components/comments/Comment.container.js
- src/client/components/comments/CommentList.component.js
- src/client/components/comments/__tests__/CommentContainer.test.js
- src/client/components/comments/__tests__/__snapshots__/CommentContainer.test.js.snap
- src/client/components/list/__tests__/Listpage.test.js
- src/client/components/list/__tests__/__snapshots__/Listpage.test.js.snap
- src/client/components/list/templates/SimpleList.component.js
- src/client/redux/__tests__/__snapshots__/comment.reducer.test.js.snap
- src/client/redux/__tests__/comment.reducer.test.js
- src/client/redux/comment.middleware.js
- src/client/redux/comment.reducer.js
- src/client/redux/root.reducer.js
- src/lib/services/elvis/community.js
> Add user profiles and limit comment ability to social lists

- package.json
- src/client/components/belt/RecentListsBelt.container.js
- src/client/components/general/CheckmarkConnected.component.js
- src/client/components/list/ListCard.component.js
- src/client/components/list/ListCreate.container.js
- src/client/components/list/ListPage.container.js
- src/client/components/list/Lists.container.js
- src/client/components/list/__tests__/ListCreate.test.js
- src/client/components/list/templates/CircleTemplate.container.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/list/templates/__tests__/CircleTemplate.test.js
- src/client/components/list/templates/__tests__/__snapshots__/CircleTemplate.test.js.snap
- src/client/components/modals/AddToListModal.container.js
- src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap
- src/client/redux/list.reducer.js
- src/client/redux/middleware.js
- src/client/utils/requestLists.js
- src/client/utils/testHelper.js
> refactor list state - make list objects be lists and not `{data,links}`,

- src/client/utils/requester.js
> workaround for bug#246

- package.json
- tools/fetch-data.js
- tools/put-data.js
make it easier to inject newest json files from jenkins job
> download json files, when injecting

- package.json
- src/client/__tests__/App.test.js
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/belt/BooksBelt.container.js
- src/client/components/bookcase/BookcaseItem.component.js
- src/client/components/filter/FilterPage.container.js
- src/client/components/frontpage/FrontPage.container.js
- src/client/redux/belts.reducer.js
- src/client/redux/books.reducer.js
- src/client/redux/filter.reducer.js
- src/client/redux/middleware.js
- src/client/redux/recommend.js
- src/client/redux/selectors.js
- src/client/utils/requester.js
Har forsøgt at rette op på performance-problemer:
- bånd renderes ikke unødvendigt 
- der hentes færre bøger ud per bånd
- bånd lazy loades (ikke elementer i bånd ved slide, men bånd indlæses ved vertikal scroll)
#188, #258
> Nye bånd på forside

- .eslintrc.js
- package-lock.json
- src/client/components/belt/RecentListsBelt.container.js
- src/client/components/comments/CommentInput.component.js
- src/client/components/comments/CommentWrapper.component.js
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/components/general/ProfileImage.component.js
- src/client/components/list/ListCard.component.js
- src/client/components/list/ListPage.container.js
- src/client/components/list/__tests__/Listpage.test.js
- src/client/components/list/__tests__/__snapshots__/Listpage.test.js.snap
- src/client/components/list/templates/CircleTemplate.container.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/list/templates/__tests__/CircleTemplate.test.js
- src/client/components/list/templates/__tests__/__snapshots__/CircleTemplate.test.js.snap
- src/client/components/profile/ProfilePage.container.js
#273 
Indsat rigtig navn og profilbillede følgende steder:
- Forside - Seneste offentlige lister
- Visuel liste (CircleTemplate)
- Simpel liste (simpleList)
> 273 correct image name

- package-lock.json
- package.json
- src/client/components/comments/CommentWrapper.component.js
- src/client/components/comments/__tests__/CommentContainer.test.js
- src/client/components/comments/__tests__/__snapshots__/CommentContainer.test.js.snap
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/style/index.css
- src/client/style/utils/emoji.css
- src/client/utils/__tests__/textParser.test.js
- src/client/utils/textParser.js
> convert links and emojis to a tags and images.

- src/client/utils/requestLists.js
- src/client/utils/requester.js
> remove duplicate pids.

- src/client/components/comments/CommentWrapper.component.js
- src/client/components/general/ProfileImage.component.js
- src/client/utils/requestLists.js
- src/client/utils/requester.js
> added user check

- src/client/utils/requestLists.js
This should solve problems with lists being duplicated, and system lists not being created.
> Do not fetch old lists

- src/client/components/bookcase/BookcaseItem.component.js
- src/client/components/bookcase/CarouselItem.component.js
- src/client/components/bookcase/__test__/__snapshots__/BookcaseÍtem.test.js.snap
- src/client/components/bookcase/__test__/__snapshots__/CarouselItem.test.js.snap
- src/client/components/general/ProfileImage.component.js
- src/client/components/list/Lists.container.js
- src/client/components/list/templates/CircleTemplate.container.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/list/templates/__tests__/__snapshots__/CircleTemplate.test.js.snap
- src/client/redux/bookcase.reducer.js
- src/client/style/components/bookcase.css
- src/client/style/components/carousel.css
- src/client/style/components/simplelist.css
#297 
Dette er ikke et endeligt pull request for #297 men indeholder en masse mindre fejl og fixes. 
Dette Issue: 
- Tilføjede beskrivelse af Helene
- Tilføjede 1 af 1 mulige af Helenes bøger + beskrivelse
- Tilføjede prioritering af bog beskrivelse, så hvis en kendt selv har tilføjet tekst til en bog, vises den fremfor selve std. bog beskrivelsen. 
Andet:
- Viser manglende 'bog data' på bøger tilføjet til system lister - Tilføjet fra bogreolen. 
- Tilføjer padding til bøger på simple lister, så 'seperator stregen' ikk står helt op i bog coverede. 
- Rettede så alle små profilbilleder kører efter ProfileImage default størrelse (35px). (kan ændres ved at angive en size="" attr på componenten.)
- Custom lister vises selvom de ikke har noget indhold
> 297 bookcase helene text

- src/client/style/components/topbar.css
#299 
Kunne lige nå den før fyraften :D
> logout hover added

- src/client/components/list/AddToList.container.js
- src/client/components/list/ListCreate.container.js
- src/client/components/list/ListPage.container.js
- src/client/components/list/__tests__/AddToList.container.test.js
- src/client/components/list/__tests__/Listpage.test.js
- src/client/components/list/__tests__/__snapshots__/AddToList.container.test.js.snap
- src/client/components/list/__tests__/__snapshots__/Listpage.test.js.snap
- src/client/components/list/templates/CircleTemplate.container.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap
- src/client/redux/list.reducer.js
- src/client/redux/middleware.js
- src/client/style/components/simplelist.css
- src/client/utils/requestLists.js
#204 
- Tilføj til åben liste
- Fjern bøger fra åben liste
Rediger beskrivelser for egne elementer i en liste kommer i #256 heri kommer der  nok også lidt styling så det nærmer sig funkys design
> Læg i åben liste

- src/client/components/general/Link.component.js
- src/client/components/list/ListCard.component.js
- src/client/style/components/listcard.css
Reverts DBCDK/content-first#326
I didn't actually mean to merge this with Master. (doh!). Still learning. I don't think anything is wrong with it, but it wasn't even finished doing the standardised testing. Sorry.
Please allow a revert, check the code and merge if ok.
> Revert "264b link stvi"

- src/acceptance/admin_no-db.js
- src/acceptance/admin_test.js
- src/acceptance/v1-recompass_test.js
- src/lib/services/recompas.js
- src/server/config.js
- src/server/external-server.js
- src/server/external-v1-recompass.js
- src/server/recompas.js
> convert recompas service to class and expose in howru endpoint

- src/client/components/list/Lists.container.js
> list link text should depend on list length

- src/client/components/modals/AddToListModal.container.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap
- src/client/redux/__tests__/list.reducer.test.js
- src/client/redux/list.reducer.js
- src/client/style/components/addtolistmodal.css
#277 løsning, som også erstatter issue #275
> 277 new list usability

- src/client/components/list/ListPage.container.js
- src/client/components/list/__tests__/__snapshots__/Listpage.test.js.snap
- src/client/components/list/templates/CircleTemplate.container.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/list/templates/__tests__/__snapshots__/CircleTemplate.test.js.snap
- src/client/redux/list.reducer.js
- src/client/style/components/simplelist.css
- src/client/style/utils/utils.css
> Rediger beskrivelser for åbne elementer

- src/client/components/comments/CommentInput.component.js
- src/client/components/comments/CommentList.component.js
- src/client/components/comments/CommentWrapper.component.js
- src/client/components/comments/__tests__/__snapshots__/CommentContainer.test.js.snap
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
> Make sure height is updated when linebreaks are added.

- src/client/components/comments/CommentInput.component.js
- src/client/components/comments/CommentWrapper.component.js
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/components/general/ProfileImage.component.js
- src/client/components/list/ListCard.component.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/top/TopBar.component.js
- src/client/style/components/comment.css
- src/client/style/components/imageUpload.css
- src/client/style/components/topbar.css
#273 rettede profile template billedet (glyphicon-user) til, så det ikke står skævt.
Tilføjede også ProfileImage componenten i topbar'en.
> changed profile image template

- src/server/external-v1-tags.js
> make suggester case insensitive.

- src/client/components/list/ListCreate.container.js
- src/client/components/list/__tests__/ListCreate.test.js
- src/client/components/list/__tests__/__snapshots__/ListCreate.test.js.snap
- src/client/components/modals/AddToListModal.container.js
- src/client/components/modals/ConfirmModal.component.js
- src/client/components/modals/Modal.container.js
- src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap
- src/client/redux/filter.reducer.js
- src/client/redux/list.reducer.js
- src/client/redux/middleware.js
- src/client/redux/modal.reducer.js
- src/server/external-v1-tags.js
> 325 delete own lists

- src/acceptance/v1-search_test.js
- src/server/external-v1-search.js
> Remove stemming from search

- src/client/components/modals/AddToListModal.container.js
- src/client/components/modals/__tests__/AddToListModal.test.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/style/components/addtolistmodal.css
- src/server/external-v1-search.js
> 357 systemlists in addtomodal

- src/client/components/work/WorkPage.container.js
#252 
Recommender implementeret på værksidens bånd
> recommender on workpage added

- src/client/components/list/ShortList.container.js
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/server/external-v1-search.js
> 346 show login

- src/client/components/belt/Slider.component.js
> 288 belt swipeback bug

- src/client/components/list/ListCreate.container.js
- src/client/components/modals/AddToListModal.container.js
- src/client/components/modals/Modal.component.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/style/components/imageUpload.css
- src/client/style/components/modal.css
added relation between checkboxes in create/update list
> 284 checkbox relations

- src/client/components/list/ListCreate.container.js
- src/client/components/list/ShortList.container.js
- src/client/components/list/ShortListDropDown.container.js
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/list/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
- src/client/components/modals/AddToListModal.container.js
- src/client/components/modals/Modal.component.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/style/components/imageUpload.css
- src/client/style/components/modal.css
#274 
Forsider og titler er gjort klikbare med Link komponenten.
> 274 make works clickable

- package-lock.json
- package.json
- src/client/components/general/SocialShareButton.component.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/style/components/simplelist.css
- src/client/style/components/socialShareButton.css
- src/client/style/index.css
#317 
Midlertidigt commit, for at teste pakken "React-Helmet" og hvordan facebook reagere på dynamiske tags.
> Helmet testing

- src/client/components/filter/EditFilters.component.js
- src/client/components/filter/SelectedFilters.component.js
- src/client/components/work/WorkPage.container.js
- src/client/style/filterpage.css
- src/client/style/utils/tags.css
- src/client/style/work.css
> 369 workpage tags

- src/client/components/general/SocialShareButton.component.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/modals/OrderModal.container.js
Skjuler facebook share knappen på liste siden. #317
> Hide facebook share button

- src/client/components/order/OrderButton.component.js
> status på bestilknap, 

- src/client/components/list/ShortList.container.js
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
merge #378  først for at få en læsevenlig diff, - eller merge blot denne, som så tager dem begge ind.
#372
> Disable "Bestil alle"-knap hvis alle bestilt 

- package-lock.json
- package.json
- src/client/components/general/SocialShareButton.component.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/modals/OrderModal.container.js
- src/client/style/components/socialShareButton.css
- src/client/style/media/fb.svg
- src/server/external-meta.js
- src/server/external-server.js
#317 
- Klar til at teste Facebot
> 317 share list on facebook

- src/acceptance/admin_no-db.js
- src/acceptance/admin_test.js
- src/lib/services/database.js
- src/lib/services/service-status.js
- src/server/external-server.js
> howru status-kode ved fejl + clear gamle fejl

- src/client/components/general/SocialShareButton.component.js
- src/client/components/general/__tests__/__snapshots__/SocialShareButton.test.js.snap
- src/client/components/list/ListCreate.container.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/style/components/socialShareButton.css
> 396 Public list check on SocialShareButton

- public/index.html
- src/client/components/general/SocialShareButton.component.js
- src/client/components/general/__tests__/__snapshots__/SocialShareButton.test.js.snap
- src/client/components/list/ListPage.container.js
- src/client/components/list/__tests__/__snapshots__/Listpage.test.js.snap
- src/client/components/list/templates/CircleTemplate.container.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/list/templates/__tests__/__snapshots__/CircleTemplate.test.js.snap
- src/client/components/work/WorkPage.container.js
- src/client/style/components/checkmarkButton.css
- src/client/style/components/checkmarkmenu.css
- src/client/style/components/simplelist.css
- src/client/style/work.css
- src/server/external-meta-list.js
- src/server/external-meta-work.js
- src/server/external-server.js
- src/server/meta-response-template.js
løser #397 
Andet: 
- Flyttede titel headeren i den visuel liste til ned under billedet
- Flyttede bestil knappen på værksiden
- Nyt FB prevent-cashing tiltag som skal testes.
> #397 facebook button on workpage

- src/client/components/list/ShortList.container.js
> 197 bugfix

- src/client/redux/user.middleware.js
> openplatform anonymous login for un-logged-in users

- src/client/redux/recommend.js
#419 
Hvis der ikke er valgt nogen custom filtre, sorteres der ingen bøger fra på value key'en.
> added filter evaluation in redux recommend

- src/client/components/bookcase/__test__/__snapshots__/CarouselItem.test.js.snap
- src/client/components/general/BookCover.component.js
- src/client/components/list/__tests__/ShortList.container.test.js
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/rollover/__test__/__snapshots__/RollOver.test.js.snap
- src/client/utils/requester.js
> Brug covers fra moreInfo/openplatform

- .gitignore
- src/client/redux/interaction.middleware.js
- src/client/redux/interaction.reducer.js
- src/client/redux/root.reducer.js
- src/client/redux/user.middleware.js
- src/index.js
Complications in GIT with the similar branch 76-track-user-behavior-stvi inspired me to make a new branch with all updates associated with this issue. The older branch should be removed.
> 76 tracking user behavior stvi

- src/client/components/follow/Follow.component.js
- src/client/components/list/ListCard.component.js
- src/client/components/list/ListItem.component.js
- src/client/components/list/Lists.container.js
- src/client/components/list/__tests__/ListItem.test.js
- src/client/components/list/__tests__/__snapshots__/ListItem.test.js.snap
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/profile/ProfilePage.container.js
- src/client/redux/__tests__/__snapshots__/follow.reducer.test.js.snap
- src/client/redux/__tests__/follow.reducer.test.js
- src/client/redux/comment.middleware.js
- src/client/redux/follow.middleware.js
- src/client/redux/follow.reducer.js
- src/client/redux/root.reducer.js
- src/client/redux/selectors.js
- src/client/redux/user.middleware.js
- src/client/style/components/follow.css
- src/client/style/components/listcard.css
- src/client/style/components/simplelist.css
- src/client/style/components/socialShareButton.css
- src/client/style/index.css
- src/client/utils/requester.js
- src/index.js
> 435 follow lists

- src/integration/seed-community.js
- src/migrations/20180529123000_covers_owner.js
- src/migrations/20180531123000_cookies_openplatform_id.js
- src/seeds/seed-db.js
- src/server/external-hejmdal.js
- src/server/external-v1-image.js
- src/server/external-v1-object.js
- src/server/object.js
- src/server/objectStore.js
Del af #430 
- Tilføjet ejer på billeder, så de kan slettes hvis brugeren slettes.
- Tilføjet openplatform-id til cookie-tabellen, (nødvendig for senere refaktorering).
- Start refaktorering af objekt-endpointet.
> GDPR - ejer på billeder

- src/client/redux/interaction.middleware.js
Adgang til brugeres interaktionsdata #473
> Bruger-historik-data skal ikke være public #473

- src/client/components/general/SocialShareButton.component.js
- src/client/components/general/__tests__/__snapshots__/SocialShareButton.test.js.snap
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/work/WorkPage.container.js
- src/client/redux/books.reducer.js
- src/client/redux/middleware.js
- src/client/redux/recommend.js
- src/client/style/work.css
- src/client/utils/requestLists.js
- src/client/utils/requester.js
bemærk dette merger ikke ned i master
Det skulle vist virke nu med inkrementel opdatering af værk
> 389 external reviews and links kasper

- src/client/components/general/SocialShareButton.component.js
- src/client/components/general/__tests__/__snapshots__/SocialShareButton.test.js.snap
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/work/WorkPage.container.js
- src/client/redux/books.reducer.js
- src/client/redux/middleware.js
- src/client/redux/recommend.js
- src/client/style/work.css
- src/client/utils/requestLists.js
- src/client/utils/requester.js
> 389 external reviews and links

- src/client/App.js
- src/client/components/Styleguide/Styleguide.component.js
- src/client/components/base/Button/Button.css
- src/client/components/base/Button/Button.js
- src/client/components/base/Button/index.js
- src/client/components/base/Heading/Heading.css
- src/client/components/base/Heading/Heading.js
- src/client/components/base/Heading/index.js
- src/client/style/global.css
- src/client/style/index.css
Also implements
* New font
* global settings
solves #459
> Add generic button component

- public/index.html
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/Heading/Heading.css
- src/client/components/base/Icon/Icon.js
- src/client/components/base/Skeleton/Text/Text.css
- src/client/components/base/Skeleton/Text/Text.js
- src/client/components/base/Skeleton/Text/index.js
- src/client/components/base/Skeleton/User/User.css
- src/client/components/base/Skeleton/User/User.js
- src/client/components/base/Skeleton/skeleton.css
- src/client/components/belt/RecentListsBelt.container.js
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/components/general/BookmarkButton.js
- src/client/components/general/ProfileImage.component.js
- src/client/components/list/ListCard.component.js
- src/client/components/list/ShortListDropDown.container.js
- src/client/components/list/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
- src/client/components/top/TopBar.component.js
- src/client/components/top/Topbar.css
- src/client/style/components/listcard.css
- src/client/style/global.css
- src/client/utils/toColor.js
- src/index.js
- src/prototypes.js
> 453 users lists frontpage

- src/client/components/top/TopBar.component.js
> event.path with firefox support

- src/client/components/bookcase/__test__/__snapshots__/CarouselItem.test.js.snap
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/components/general/BookCover.component.js
- src/client/components/general/ProfileImage.component.js
- src/client/components/list/BookSearchSuggester.js
- src/client/components/list/ListItem.component.js
- src/client/components/list/Lists.container.js
- src/client/components/list/__tests__/__snapshots__/AddToList.container.test.js.snap
- src/client/components/list/__tests__/__snapshots__/ListItem.test.js.snap
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/rollover/__test__/__snapshots__/RollOver.test.js.snap
- src/client/components/top/Topbar.css
- src/client/components/work/WorkCard.css
- src/client/components/work/WorkPage.container.js
- src/client/redux/middleware.js
- src/client/utils/requestLists.js
- src/client/utils/requester.js
Løser: #510 og #503 
+ ændret fetchBooks til at tage en store som 2. parameter (#503 )
+ henter coverUrl til preview visning på listesiden
+ justering af default billedet, når en bruger ikke har et profilebillede. (profileImage component)
> 510-listpage-book-preview + extra

- src/server/knexfile.js
(same as already present in prod-section of file)
> make number of database connections configurable in CI and dev

- src/client/components/belt/BooksBelt.container.js
- src/client/components/general/CheckmarkConnected.component.js
- src/client/components/list/ListCard.component.js
- src/client/components/list/ListCreate.container.js
- src/client/components/list/ListItem.component.js
- src/client/components/list/ListPage.container.js
- src/client/components/list/Lists.container.js
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/modals/AddToListModal.container.js
- src/client/components/work/WorkItemConnected.component.js
- src/client/components/work/WorkPage.container.js
- src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap
- src/client/redux/__tests__/list.reducer.test.js
- src/client/redux/list.reducer.js
- src/client/redux/middleware.js
- src/client/utils/requestLists.js
> BooksReducer in Lists

- src/client/components/general/CheckmarkConnected.component.js
No issue
- fix til content-first viser blank side
> moved .book

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/Button/Button.css
- src/client/components/base/Button/Button.js
- src/client/components/base/Heading/Heading.css
- src/client/components/base/Heading/Heading.js
- src/client/components/base/Skeleton/skeleton.css
- src/client/components/belt/BooksBelt.container.js
- src/client/components/belt/InteractionsRecoBelt.container.js
- src/client/components/belt/Slider.component.js
- src/client/components/belt/Slider.css
- src/client/components/frontpage/FrontPage.container.js
- src/client/components/general/AddToListButton.component.js
- src/client/components/general/AddToListButton.css
- src/client/components/general/BookmarkButton.css
- src/client/components/general/BookmarkButton.js
- src/client/components/list/ListCard.component.js
- src/client/components/list/ShortList.container.js
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/order/OrderButton.component.js
- src/client/components/work/WorkCard.container.js
- src/client/components/work/WorkPage.container.js
- src/client/components/work/WorkPage.css
- src/client/components/work/WorkPreview.component.js
- src/client/components/work/WorkPreview.css
- src/client/redux/belts.reducer.js
- src/client/style/App.css
- src/client/style/global.css
- src/client/style/index.css
løser #518 og #490
OBS issue #490 (på værksiden) løses først i issue #461
> 518 workview frontpage

- src/client/components/base/Button/Button.css
- src/client/components/general/AddToListButton.css
- src/client/components/general/BookmarkButton.css
- src/client/components/work/WorkPage.css
- src/client/components/work/WorkPreview.css
hurtig lille fix til nogen overskredet styles i issue #518 som blev merged ind i PR #531
> 518-workview-frontpage - styles

- src/acceptance/1-user_test.js
- src/server/external-v1-user.js
- src/server/user.js
Bemærk at indtil #538 er merget, vil sletning medfører at brugeren bliver resat til hvad der ligger af gamle data i communityservicen. Efter denne er merget, vil sletning være ægte sletning.
> user delete api, #430

- package-lock.json
- package.json
- src/client/components/belt/templates/BooksBelt.container.js
- src/client/components/work/WorkCard.container.js
- src/client/components/work/WorkPreview.component.js
> 528 scroll to books-belt

- src/client/components/list/ListDrag.component.js
- src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap
- src/client/redux/__tests__/list.reducer.test.js
- src/client/redux/list.reducer.js
> fix duplicate elements bug when reordering elements in a list

- src/client/components/list/ListOverviewDropDown.container.js
- src/client/components/list/dropdownList.css
- src/client/components/top/TopBar.component.js
> listsdropdown-blocking-profile-button bug fixed

- src/client/components/list/ListOverviewDropDown.container.js
> 'Af' added in front of username in listsoverview

- src/client/components/belt/templates/BooksBelt.container.js
- src/client/components/work/WorkCard.container.js
> scroll down + belt width issue fixed

- src/client/utils/requester.js
> default owner not null but undefined

- package-lock.json
- src/client/App.js
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/filter/FilterPage.container.js
- src/client/components/filter/Filters.component.js
- src/client/components/filter/Filters.css
- src/client/components/filter/SearchBar.component.js
- src/client/components/filter/SearchBar.css
- src/client/components/filter/SelectedFilters.component.js
- src/client/components/filter/TagsSuggester.component.js
- src/client/components/frontpage/FrontPage.container.js
- src/client/components/list/ListCreate.container.js
- src/client/components/list/Lists.container.js
- src/client/components/list/ShortList.container.js
- src/client/components/list/__tests__/__snapshots__/ListCreate.test.js.snap
- src/client/components/list/__tests__/__snapshots__/ListsContainer.test.js.snap
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/profile/CreateProfilePage.js
- src/client/components/profile/ProfilePage.container.js
- src/client/components/profile/__tests__/__snapshots__/CreateProfile.test.js.snap
- src/client/components/top/TopBar.component.js
- src/client/components/top/Topbar.css
- src/client/components/work/WorkCard.container.js
- src/client/components/work/WorkPage.container.js
- src/client/style/App.css
- src/client/style/components/simplelist.css
- src/client/style/filterpage.css
- src/client/style/index.css
> 590 filterpage adjustments

- src/client/components/bookcase/__test__/__snapshots__/CarouselItem.test.js.snap
- src/client/components/general/BookCover.component.js
- src/client/components/list/ShortListDropDown.container.js
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/list/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
- src/client/components/list/dropdownList.css
- src/client/components/rollover/__test__/__snapshots__/RollOver.test.js.snap
- src/setupTests.js
> 584 shortlist covers kfu

- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/components/general/Spinner.component.js
- src/client/components/profile/CreateProfilePage.js
- src/client/components/profile/__tests__/__snapshots__/CreateProfile.test.js.snap
- src/client/components/search/__tests__/__snapshots__/SearchField.test.js.snap
- src/client/redux/user.middleware.js
- src/client/redux/user.reducer.js
- src/client/style/components/modal.css
- src/client/style/components/profile.css
- src/client/style/utils/spinner.css
- src/client/utils/requester.js
Sidste brik i slet profil spillet. 
Løser issue #446
> 446 delete profile

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/list/ShortListDropDown.container.js
- src/client/components/list/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
- src/client/components/list/dropdownList.css
> shortlist close btn

- src/client/components/modals/AddToListModal.container.js
> clear shortlist

- src/client/components/bookcase/Bookcase.component.js
- src/client/components/bookcase/BookcaseItem.component.js
- src/client/style/components/bookcase.css
The new design among other things removed the choice of other celebs, so the functionality involved there was also removed.  Text truncating functionality was also removed to fit design.  The naming convention and structure was changed somewhat to fit new text. Some static variables were added.
> initial commit, redesign after changes to master

- src/client/components/work/WorkPreview.css
> work preview width issue fixed

- src/client/components/list/ListCreate.container.js
- src/client/components/list/ListPage.container.js
- src/client/components/list/__tests__/__snapshots__/ListCreate.test.js.snap
- src/client/redux/list.reducer.js
> only support simple list template, fix upload list image

- src/client/components/Styleguide/Styleguide.component.js
- src/client/components/base/ContextMenu/ContextMenu.css
- src/client/components/base/ContextMenu/ContextMenu.js
- src/client/components/base/ContextMenu/index.js
> added context menu component

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/bookcase/BookcaseItem.component.js
- src/client/components/list/ShortList.container.js
- src/client/components/list/ShortListDropDown.container.js
- src/client/components/list/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/list/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
- src/client/components/list/dropdownList.css
- src/client/components/list/templates/SimpleList.component.js
- src/client/components/modals/AddToListModal.container.js
- src/client/components/modals/ConfirmModal.component.js
- src/client/components/modals/LoginModal.component.js
- src/client/components/modals/Modal.component.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/components/modals/__tests__/__snapshots__/LoginModal.test.js.snap
- src/client/style/components/bookcase.css
- src/client/style/components/modal.css
- src/client/style/components/simplelist.css
- src/client/style/global.css
> svg-icons replaced with material

- src/client/components/base/ToastMessage/ToastMessage.js
- src/client/components/filter/TagsSuggester.component.js
> Filterpage arrow up down

- src/client/components/general/AddToListButton.component.js
- src/client/components/list/ShortList.container.js
- src/client/components/modals/AddToListModal.container.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/redux/modal.reducer.js
- src/client/utils/testHelper.js
> 626 add to list modal bugs

- src/client/components/general/AddToListButton.component.js
- src/client/components/general/AddToListButton.css
løser issue: #647 
Løser også et "nyt" opstået issue med addToList visningen på mobil, som ikke blev vist korrekt.
> 647 add to list login modal bug

- src/client/components/filter/Filters.component.js
- src/client/redux/filtercard.reducer.js
> Listcard behavior changes

- src/client/components/list/ListOverviewDropDown.container.js
> listoverview close btn

- src/client/components/list/ShortListDropDown.container.js
- src/client/components/work/TaxDescription.component.js
- src/client/components/work/WorkCard.container.js
- src/client/components/work/WorkItem.component.js
- src/client/components/work/WorkPage.container.js
- src/client/components/work/WorkPreview.component.js
> 678 taxdesc component

- src/client/components/list/shortlist/ShortList.container.js
> moving books from shortlist issue fixed

- src/client/utils/requester.js
> search issue with '&' fixed

- src/client/components/profile/CreateProfilePage.js
- src/client/components/profile/UserProfileForm.component.js
- src/client/components/profile/__tests__/__snapshots__/CreateProfile.test.js.snap
- src/client/components/profile/__tests__/__snapshots__/UserProfileForm.test.js.snap
> 689 edit profile bug

- src/client/redux/replay.js
> 526 session storage

- src/client/components/filter/TagsSuggester.component.js
- src/client/utils/requester.js
> search with comma issue fixed

- src/client/redux/order.middleware.js
løser issue: #716 
Ændrede Openplatform v2 depricated library (id) attribut til Openplatform v3 nye attribut pickUpBranch (id)
> 716 bestil bøger på Openplatform V3

- src/client/components/frontpage/FrontPage.container.js
Ny id til bogreolen på forsiden.
> bookcase id change

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/list/overview/dropdownList.css
- src/client/components/list/shortlist/ShortListDropDown.container.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
løser issue: #712 
max-height tilføjet til huskeliste og liste oversigt i topbaren (Max 80% af viewportens højde)
> 712 shortlist height on small screens

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/bookcase/BookcaseItem.component.js
- src/client/components/filter/FilterPage.container.js
- src/client/components/filter/Filters.component.js
- src/client/components/filter/SearchBar.css
- src/client/components/filter/TagsSuggester.component.js
- src/client/components/frontpage/FrontPage.container.js
- src/client/components/general/AddToListButton.css
- src/client/components/work/WorkCard.container.js
- src/client/components/work/WorkPage.container.js
- src/client/style/components/concisework.css
- src/client/style/filterpage.css
løser issue: #729 #714 #711 #710
> Ipad enhancements

- src/client/redux/recommend.js
> search filters work length issue fixed

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/top/TopBar.component.js
- src/client/components/top/Topbar.css
> topbar logo modified

- src/client/components/base/Text/Text.css
- src/client/components/bookcase/BookcaseItem.component.js
- src/client/components/bookcase/__test__/__snapshots__/BookcaseItem.test.js.snap
- src/client/components/list/templates/bookcase/BookcaseList.js
- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/list/templates/bookcase/bookcaseList.css
- src/client/components/pulse/Pulse.component.js
- src/client/components/pulse/__test__/__snapshots__/Pulse.test.js.snap
- src/client/style/components/pulse.css
- src/client/utils/timeToString.js
> 743 bookcase patches

- src/client/components/general/SocialShareButton.component.js
- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/list/templates/simple/ListInfo.js
- src/client/components/top/TopBar.component.js
- src/client/components/work/WorkPage.container.js
- src/client/components/work/WorkPreview.component.js
> facebook share urls updated

- src/client/components/general/SocialShareButton.component.js
- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/list/templates/simple/ListInfo.js
- src/client/components/top/TopBar.component.js
- src/client/components/work/WorkPage.container.js
- src/client/components/work/WorkPreview.component.js
This reverts commit 6f0a3e386858c88562c70c267f1eebb38e0f369c, reversing
changes made to f9a1cce6cae57cf6fb9392915f4edd53c05886f2.
> Revert "Merge pull request #747 from DBCDK/691-facebook-url"

- package-lock.json
- package.json
- src/client/components/list/menu/ListContextMenu.js
- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/modals/Modal.component.js
- src/client/components/modals/Modal.container.js
- src/client/components/modals/Modal.css
- src/client/components/modals/ReorderListModal.container.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/components/top/TopBar.component.js
- src/client/redux/modal.reducer.js
- src/client/style/index.css
> 616 reorder list elements

- src/client/components/general/__tests__/SocialShareButton.test.js
- src/client/components/general/__tests__/__snapshots__/SocialShareButton.test.js.snap
- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/list/templates/simple/ListInfo.js
- src/client/components/work/WorkPage.container.js
- src/client/components/work/WorkPreview.component.js
> socialshare urls updated

- src/client/components/list/button/FollowButton.js
> update follow label

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/belt/RecentListsBelt.container.js
- src/client/components/follow/Follow.component.js
- src/client/components/general/AddToListButton.component.js
- src/client/components/list/card/ListCard.component.js
- src/client/components/list/overview/ListItem.component.js
- src/client/components/list/overview/ListOverviewDropDown.container.js
- src/client/components/list/overview/Lists.container.js
- src/client/components/modals/AddToListModal.container.js
- src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap
- src/client/redux/__tests__/list.reducer.test.js
- src/client/redux/list.reducer.js
- src/client/redux/middleware.js
- src/client/redux/selectors.js
- src/client/redux/user.middleware.js
- src/client/redux/users.js
- src/client/utils/requestLists.js
- src/setupTests.js
- Mulighed for at hente lister man følger. Før hentede den bare de seneste offentlige lister, og hvis man så tilfældigvis fulgte dem, blev de vist.
- Egne lister hentes stadig ved page-load, da der er visse komponenter der ikke fungerer ordentligt, medmindre de er indlæst fra start (addToListModal+Button)
- Optimering af enrichList, så der kun foretages ét request der henter alle listens elementer ud, i stedet for et request per element.
- Rodet lidt mere med reselect selectors for at undgå unødvendige renders
> fetch lists when they are actually needed, and stuff

- src/client/components/list/addtolist/AddToList.container.js
- src/client/components/list/addtolist/__tests__/__snapshots__/AddToList.container.test.js.snap
- src/client/components/list/button/StickyConfirmPanel.js
- src/client/components/list/templates/bookcase/BookcaseList.js
- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/list/templates/simple/ListInfo.js
- src/client/components/list/templates/simple/SimpleList.js
> 698 new list bugs

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/belt/RecentListsBelt.container.js
- src/client/components/belt/templates/BooksBelt.container.js
- src/client/components/frontpage/FrontPage.container.js
- src/client/components/general/AddToListButton.component.js
- src/client/components/general/BookCover.component.js
- src/client/components/work/WorkCard.container.js
- src/client/components/work/WorkCard.css
- src/client/components/work/WorkPreview.component.js
- src/client/components/work/WorkPreview.css
> 771 belt tablet interaction

- package-lock.json
- src/client/components/list/templates/bookcase/BookcaseList.js
- src/client/components/list/templates/bookcase/ListInfo.js
> safari bookcase img issue fixed

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/Title/Title.css
- src/client/components/belt/RecentListsBelt.container.js
- src/client/components/belt/Slider.css
- src/client/components/belt/templates/BooksBelt.container.js
> 787 Belt Headings to Title

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/belt/templates/BooksBelt.container.js
- src/client/components/bookcase/BookcaseItem.component.js
- src/client/components/bookcase/__test__/__snapshots__/BookcaseItem.test.js.snap
- src/client/redux/belts.reducer.js
- src/client/style/components/bookcase.css
løser små kosmetiske ting på bogreolen (forsiden)
> Bookcase fixes

- src/client/components/base/Button/Button.css
- src/client/components/general/BookmarkButton.css
> hover color on touch devices  fixed

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/top/TopBar.component.js
> Show shortlist length on mobile devices

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/Text/Text.css
- src/client/components/modals/ConfirmModal.component.js
- src/client/components/modals/Modal.component.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/components/top/TopBar.component.js
- src/client/components/top/Topbar.css
Implementering af design og funktionalitet fra issue: #772
> 772 beta modal

- src/client/components/base/Text/Text.css
- src/client/components/comments/Comment.container.js
- src/client/components/comments/CommentInput.component.js
- src/client/components/comments/CommentList.component.js
- src/client/components/comments/CommentWrapper.component.js
- src/client/components/comments/__tests__/CommentContainer.test.js
- src/client/components/comments/__tests__/CommentWrapper.test.js
- src/client/components/comments/__tests__/__snapshots__/CommentContainer.test.js.snap
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/components/list/element/ListElement.js
- src/client/style/components/comment.css
> new comment field design

- src/client/components/hero/Hero.component.js
- src/client/components/hero/Hero.css
Tvininger searchbaren frem i Hero, når en tablet eller mobil holdes i landscape mode.
> 784 hero width+small+fixes

- src/client/components/top/TopBar.component.js
Bliv på samme side når der klikkes på "Læs mere"
> Beta modal fix

- src/client/components/general/BookCover.component.js
- src/client/components/work/WorkRow.js
> bookcase align in listview

- src/client/components/general/SocialShareButton.component.js
- src/client/components/general/__tests__/__snapshots__/SocialShareButton.test.js.snap
- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/list/templates/simple/ListInfo.js
>  prevent sharing private lists on facebook

- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/list/templates/simple/ListInfo.js
- src/client/components/modals/ConfirmModal.component.js
- src/client/components/modals/Modal.component.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
> popup block from browser in list sharing fixed

- src/client/components/list/templates/simple/ListInfo.js
- src/server/internal-server.js
- src/server/internal-v1-test-login.js
- src/server/internal-v1-test.js
- src/server/internal-v1.js
> login simulation endpoint implemented

- src/acceptance/v1-stats_test.js
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/top/TopBar.component.js
- src/client/components/top/Topbar.css
- src/client/redux/root.reducer.js
- src/client/redux/stats.middleware.js
- src/client/redux/stats.reducer.js
- src/client/utils/requester.js
- src/fixtures/schemas/public-statistics-out.json
- src/index.js
- src/server/external-v1-stats.js
- src/server/external-v1.js
Fetch number of books and put that number in the header on the GUI.
> 809 number of books slf

- src/client/utils/requester.js
- src/index.js
removed console statements + added forgotten comma in index.js
> Yellow Pipeline error - merge conflict

- src/client/components/filter/FilterPage.container.js
- src/client/components/filter/SearchBar.component.js
> 863 - Filterpage: Quickfix for clearing book previews and "more like this" sections

- src/client/components/comments/CommentWrapper.component.js
- src/client/redux/comment.reducer.js
> CF-847 comment bug

- src/client/utils/requester.js
> 472 - Shortlist: books deleted on user edit

- src/client/components/spots/Spots.css
> 723 iOS smooth scroll in spot container

- src/client/components/belt/templates/BooksBelt.container.js
- src/client/components/belt/templates/InteractionsRecoBelt.container.js
There was also a warning about a missing key in the booksbelt.container that I fixed while I was in there.
> 864 forslag username stvi

- package-lock.json
- package.json
- src/client/components/comments/CommentWrapper.component.js
- src/client/components/general/BookCover.component.js
- src/client/components/general/BookCover.css
- src/client/components/top/TopBar.component.js
- src/client/components/work/WorkPage.container.js
> CF-730 lightbox

- src/client/components/hero/Hero.css
- src/server/external-v1-auth.js
Løser issue CF-758 og CF-860
+ ændret søge ikon farve i Hero
> 758 keep filter values in url on login

- package.json
- src/client/components/list/menu/StickySettingsPanel.js
- src/client/components/list/templates/bookcase/BookcaseList.js
- src/client/components/list/templates/simple/SimpleList.js
> CF-825 disable add to list btn 

- cypress/integration/login.spec.js
- src/client/components/comments/CommentWrapper.component.js
- src/server/external-server.js
- src/server/internal-v1-test.js
> CF-868 testlogin & cypress test updated 

- src/client/redux/user.middleware.js
> CF-870 profile deletion issue fixed

- package-lock.json
- src/client/components/filter/TagsSuggester.component.js
Dette er på ingen måde en perfekt løsning - men suggesteren opfatter nu ikke længere specialtegn som stop tegn.
> Speial tegn ignoreres nu af suggesteren

- src/client/components/list/menu/StickySettingsPanel.js
- src/client/redux/replay.js
- src/client/redux/user.middleware.js
> 860 + 758 - back to page after login

- src/client/redux/filter.reducer.js
Der er sket en ændring i taksonomi, som kræver rettelse af filter-siden
> fix filter page

- src/client/App.js
- src/client/components/modals/Modal.component.js
- src/client/utils/localstorage.js
> CF-677 cookies block

- src/client/components/work/ResumeReview.component.js
- src/client/components/work/Review.css
- src/client/components/work/__tests__/__snapshots__/ResumeReview.component.test.js.snap
Peter ønsker små bogstaver for "Bibliotekernes vurdering", Lektørnavn og "Læs materialevurderingen" - men kun under Workpreview - ikke i den udfoldede visning.
Afventer godkendelse af Peter
> Flere rettelser til Lektørudtalelser, indrapporteret af Peter

- package-lock.json
- package.json
- src/client/App.js
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/general/CookieWarning/CookieWarning.css
- src/client/components/general/CookieWarning/CookieWarning.js
> CF-912 cookie warning

- src/client/App.js
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/list/overview/ListOverviewDropDown.container.js
- src/client/components/top/TopBar.component.js
> CF-1002 removed listpage

- package-lock.json
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/T/T.json
- src/client/components/filter/Results.component.js
- src/client/components/general/Footer.component.js
- src/client/components/general/Footer.css
- src/client/components/list/overview/ListOverviewDropDown.container.js
løser issue: CF-946 og CF-1039
> Footer i fuld bredde

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/article/Article.component.js
- src/client/components/article/Article.css
- src/client/components/article/pages/about.md
- src/client/redux/article.reducer.js
> Implementering: Nyt artikel design

- src/server/external-server.js
> add timings log event

- src/client/components/list/overview/ListOverviewDropDown.container.js
- src/client/components/modals/OrderModal.container.js
- src/client/components/modals/__tests__/__snapshots__/OrderModal.test.js.snap
> CF-1026 - T returns Object Object

- Jenkinsfile
SOLVES [CF-1010]
[CF-1010]: https://dbcjira.atlassian.net/browse/CF-1010
> Update image tag on staging configuration

- src/client/components/list/overview/ListOverviewDropDown.container.js
> removed listpage link

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/T/T.json
- src/client/components/filter/TagsSuggester.component.js
- src/client/components/top/TopBar.component.js
also fixed a new bug that shows up when hitting the suggesters cancel button on mobile version
> changed placeholder text, focal point set to search field after cancel.

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/T/T.json
- src/client/components/filter/TagsSuggester.component.js
- src/client/components/top/TopBar.component.js
Reverts DBCDK/content-first#928
Fordi der opstår problemer på listesiden nu man redigerer kommentar til indlæg.
> Revert "changed placeholder text, focal point set to search field after cancel."

- src/client/components/base/Recommender/withQueryToPids.hoc.js
Ved forfatter-søgning sættes ekstra parameter
> merge workid

- Dockerfile
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/Text/Text.css
- src/client/components/base/Title/Title.css
- src/client/components/list/templates/bookcase/BookcaseList.js
- src/client/components/modals/OrderModal.container.js
- src/client/components/top/TopBar.component.js
- src/client/components/work/WorkPage.container.js
- src/client/components/work/WorkPreview.component.js
> Small patches before launch

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/Belt/InteractionsBelt.component.js
- src/client/components/base/Belt/RecentListsBelt.container.js
- src/client/components/base/Belt/SimilarBelt.component.js
- src/client/components/base/Belt/Slider.component.js
- src/client/components/base/Belt/Slider.css
- src/client/components/base/Belt/TagsBelt.component.js
- src/client/components/base/Belt/WorkSlider.component.js
- src/client/components/base/Belt/similarBelt.css
- src/client/components/base/Belt/withChildBelt.hoc.js
- src/client/components/frontpage/FrontPage.container.js
- src/client/components/general/BookCover.component.js
- src/client/components/general/BookmarkButton.css
- src/client/components/hero/templates/Info.css
- src/client/components/spots/Spots.container.js
- src/client/components/work/WorkCard.container.js
- src/client/components/work/WorkCard.css
- src/client/components/work/WorkPreview.component.js
- src/client/components/work/WorkPreview.css
- src/client/style/components/listcard.css
- src/client/style/global.css
> Belt redesign

- package-lock.json
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/filter/SearchBar.component.js
- src/client/components/filter/TagsSuggester.component.js
- src/client/components/top/TopBar.component.js
> 888 fixes to topbar stvi

- src/client/redux/router.reducer.js
> Url values not working for shared links

- src/client/App.js
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/Belt/TagsBelt.component.js
- src/client/components/base/Belt/TagsBelt.css
- src/client/components/base/List/withList.hoc.js
- src/client/components/base/T/T.json
- src/client/components/general/Footer.css
- src/client/components/general/Link.component.js
- src/client/components/list/addtolist/BookSearchSuggester.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
- src/client/components/modals/ListModal.component.js
- src/client/style/components/listSuggest.css
løser issue Cf-1154
+ Der kommer nu toast ved liste oprettelse
+ Fjernet Diblio O ved pinned bånd
+ Skiftet "Opret liste" til "Redigér liste" - når man åbner rediger/opret modalen
> Cf 1154 list footer fixes

- src/client/components/general/BookCover.component.js
- src/client/components/general/BookmarkButton.css
- src/client/components/general/BookmarkButton.js
- src/client/components/work/WorkCard.container.js
- src/client/components/work/WorkPage.container.js
- src/client/components/work/WorkPage.css
- src/client/components/work/WorkPreview.component.js
- src/client/components/work/WorkPreview.css
Løser issue: CF-1066 
"Huske"-knap på alle værk cover istedet for knap
> CF-1066 BookmarkButton på cover istedet for "huske"-knap. 

- src/client/components/work/Review/PaperReview.component.js
- src/client/components/work/Review/ReviewList.component.js
> firefox date format issue fixed

- src/client/components/general/BookCover.component.js
- src/client/components/hero/Hero.component.js
- src/client/components/hero/explorer/explorer.component.js
- src/client/components/hero/explorer/explorer.css
- src/client/components/hero/templates/Info.template.js
- src/client/components/hero/templates/Searchbar.template.js
- src/client/components/work/Review/Review.css
- src/client/components/work/Review/ReviewList.component.js
- src/client/components/work/WorkPage.container.js
- src/client/components/work/WorkPreview.component.js
- src/client/components/work/WorkPreview.css
løser issue Cf-1016
+ clickScroll på hero teksten "Opdag en bog og lån den ...."
+ rettet bookcover bookmark button i chrome
> Cf 1016 litteratursiden redesign

- src/client/components/base/Skeleton/Text/Text.css
- src/client/components/general/BookCover.component.js
- src/client/components/list/overview/dropdownList.css
- src/client/components/work/Review/ReviewList.component.js
- src/client/components/work/WorkCard.css
- src/client/components/work/WorkPage.css
- src/client/components/work/WorkPreview.component.js
- src/client/components/work/WorkPreview.css
- src/client/style/components/bookcover.css
- src/client/style/components/listSuggest.css
Små rettelser som relaterer til hinanden. 
løser issue: 
- CF-1016
- CF-1066
- CF-1167
> Cf 1016 1066 fixes

- src/client/components/base/RemindsOf/RemindsOf.css
- src/client/components/base/T/T.json
- src/client/components/general/BookCover.component.js
- src/client/components/list/overview/dropdownList.css
- src/client/components/modals/OrderModal.container.js
- src/client/components/modals/__tests__/__snapshots__/OrderModal.test.js.snap
- src/client/components/spots/Spots.css
- src/client/components/work/WorkCard.css
- src/client/components/work/WorkPage.container.js
- src/client/components/work/WorkPage.css
- src/client/components/work/WorkPreview.component.js
- src/client/components/work/WorkPreview.css
> Style fixes + coverimage fixes

- src/client/App.js
- src/client/components/filter/FilterCards.component.js
- src/client/components/filter/SearchBar.component.js
- src/client/components/modals/LoginModal.component.js
- src/client/components/modals/Modal.component.js
- src/client/components/modals/__tests__/__snapshots__/AddToListModal.test.js.snap
- src/client/style/index.css
> CF-1060-bigger-touch-area

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/general/FeedbackButton.component.js
- src/client/components/general/FeedbackButton.css
> fixed feedback button

- src/client/components/filter/templates/CardRange.css
> CF-1059 - Removed grey "in-active" color on range slider

- src/client/components/base/List/withList.hoc.js
- src/client/components/base/T/T.json
- src/client/components/general/AddToListButton.component.js
- src/client/components/general/AddToListButton.css
- src/client/components/hero/explorer/explorer.css
- src/client/components/modals/ListModal.component.js
- src/client/components/modals/Modal.container.js
- src/client/utils/converter.js
> Cf 945 redesign addtolist

- src/client/components/general/AddToListButton.css
- src/client/components/list/element/ListElement.js
- src/client/components/work/WorkPage.container.js
- src/client/components/work/WorkPage.css
> CF-977-style-fixes

- src/client/components/filter/templates/CardList.component.js
- src/client/components/filter/templates/CardList.css
> CF-967 hoverbug on touchdevices

- src/client/components/general/AddToListButton.component.js
- src/client/components/general/AddToListButton.css
- src/client/style/filterpage.css
løser issue: CF-1181
+ ekstra whitespace på søgesiden (på små devices) - så footeren ikke bliver så overvældende på mobil.
> CF-1181 AddToList enhancements

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/T/T.json
- src/client/components/list/overview/ListOverviewDropDown.container.js
- src/client/components/list/overview/dropdownList.css
- src/client/components/list/shortlist/ShortList.container.js
- src/client/components/list/shortlist/ShortListDropDown.container.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
- src/client/components/modals/LoginModal.component.js
- src/client/components/modals/Modal.component.js
- src/client/components/modals/__tests__/__snapshots__/LoginModal.test.js.snap
- src/client/components/top/TopBar.component.js
- src/client/style/components/modal.css
> listview modal

- src/client/components/general/BookCover.component.js
- src/client/components/modals/Modal.css
- src/client/components/modals/ReorderListModal.container.js
Bookcover fixet i "Rediger rækkefølge" på listeside
Bookcover fixet i "Tilføj til liste" på listesiden
> Bookcover fixes

- src/client/components/list/overview/dropdownList.css
> mobile view list height fixed

- src/client/components/work/WorkPreview/WorkPreview.component.js
- src/client/components/work/WorkPreview/WorkPreview.css
> CF-1198 fixed workpreview arrow position

- src/client/components/list/addtolist/BookSearchSuggester.js
- src/client/components/modals/Modal/Modal.css
Løser issue: CF-1195
+ recovered broken css in modal.css from previous pull requst (frontend-cleaning)
> CF-1195 - suggester match

- src/client/components/profile/EditProfileForm.component.js
- src/client/components/profile/EditProfilePage.js
> do not store user when undo is pressed

- src/client/components/base/List/withList.hoc.js
- src/client/components/general/AddToListButton/AddToListButton.component.js
- src/client/components/general/AddToListButton/AddToListButton.css
- src/client/components/list/shortlist/ShortList.container.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/modals/Modal/Modal.css
> CF-1203 add multiple books to list

- src/client/components/base/T/T.json
- src/client/components/base/Work/withWork.hoc.js
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/components/general/Spinner/Spinner.component.js
- src/client/components/list/shortlist/ShortList.container.js
- src/client/components/list/shortlist/__tests__/ShortList.container.test.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/order/OrderButton.component.js
- src/client/components/order/orderButton.css
- src/client/components/work/WorkPage/WorkPage.container.js
- src/client/components/work/WorkPreview/WorkPreview.component.js
- src/client/components/work/workFunctions.js
- src/client/utils/dateTimeFormat.js
Løser issue: CF-1172
+ tilføjet manglende spinner.css fil til spinner komponent.
> CF-1172 Check "Bog" type availability

- src/client/components/work/WorkPreview/WorkPreview.component.js
- src/client/components/work/WorkPreview/WorkPreview.css
> fixed workpreview arrow position

- src/acceptance/user-test-commons.js
- src/client/utils/requester.js
- src/server/user.js
> CF-1173 alternative handling of unassigned user 

- src/client/components/base/T/T.json
Fejlen med at profil billedet forsvinder kunne ikke genskabes. Så den er ikke løst.
Så - reviewet her er blot på at ændre et komma til et punktum, og slette et punktum...
> Change comma to dot, and remove trailing dot after question mark

- tools/put-data.js
Løser https://dbcjira.atlassian.net/browse/CF-1221
> take union of tags when same pid occurs multiple times

- src/client/components/general/BookCover/BookCover.component.js
- src/client/utils/splitLine.js
CF-1064 is the DESIGN - this is actually CF-1065
> #CF-1064: Split long titles in svg covers

- src/server/external-v1-recompass.js
Laves for at finde ud af om det er recommender eller content-first der giver mærkelige forslag i "minder om"-bånd
> add debug logging for recompas

- package-lock.json
- src/client/components/base/Belt/SimilarBelt.component.js
- src/client/components/base/Belt/TagsBelt.component.js
- src/client/components/base/Origin/Origin.js
- src/client/components/base/Origin/index.js
- src/client/components/base/Origin/origin.css
- src/client/components/base/T/T.json
- src/client/components/filter/FilterPage/Results.component.js
- src/client/components/list/element/ListElement.js
- src/client/components/list/shortlist/ShortList.container.js
- src/client/components/list/shortlist/ShortListDropDown.container.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
added links to shortlist and shortlist dropdown
to link back to where each book on the list was marked:
under minder om, 
lists, and 
collection of search tags.
> 1134 link in shortlist stvi

- public/index.html
- src/client/components/work/workFunctions.js
Løser issue: CF-1236 + CF-1238
> listeIndstillinger + svanebog fix

- src/client/components/profile/EditProfilePage.css
> CF-1171 fixed lang scroll in mobile view

- src/client/components/comments/CommentCounter.component.js
- src/client/components/list/templates/bookcase/BookcaseList.js
- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/list/templates/simple/ListInfo.js
- src/client/components/list/templates/simple/SimpleList.js
> CF-1220 scroll down on comment list click

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/frontpage/FrontPage.container.js
- src/client/redux/belts.reducer.js
- src/client/redux/recommend.js
Ensretter belt.reducer + løser bug med key() function
> Belts reducer cleanup

- src/client/components/hero/templates/Info.css
- src/client/components/hero/templates/Info.template.js
- src/client/components/hero/templates/InteractionSlide.css
- src/client/redux/hero.reducer.js
> Små hero tilretninger

- src/client/components/modals/ProfileModal/ProfileModal.css
> CF-1171-scroll bug on small screens fixed

- docker/env.docker
- e2e/cypress/fixtures/orderActions.json
- e2e/cypress/integration/filter.spec.js
- e2e/cypress/integration/list.spec.js
- e2e/cypress/integration/order.spec.js
- e2e/cypress/support/commands.js
- src/client/components/base/Belt/MultiRowContainer.js
- src/client/components/base/Belt/SimilarBelt.component.js
- src/client/components/filter/FilterCards/FilterCards.css
- src/client/components/filter/FilterCards/templates/CardList.component.js
- src/client/components/modals/OrderModal.container.js
- src/client/components/work/WorkCard/WorkCard.container.js
- src/index.js
Alle tests - undtagen List Tests (som fikses af Kasper) kører nu uden fejl
> 1239 faa alle cypress tests til at koere uden fejl slf

- src/client/components/list/card/ListCard.component.js
- src/client/components/list/element/ListElement.js
- src/client/components/list/templates/bookcase/BookcaseList.js
- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/list/templates/simple/SimpleList.js
- src/client/components/modals/ListModal/ListModal.component.js
- src/client/components/pulse/Pulse.component.js
- src/client/components/pulse/__test__/Pulse.test.js
- src/client/redux/list.reducer.js
> fetching comments in listcard

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/redux/belts.reducer.js
> Opdatering af forside indhold 01

- src/client/components/comments/CommentInput.component.js
- src/client/components/comments/__tests__/__snapshots__/CommentContainer.test.js.snap
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/components/list/addtolist/AddToList.container.js
- src/client/components/list/addtolist/__tests__/AddToList.container.test.js
- src/client/components/list/addtolist/__tests__/__snapshots__/AddToList.container.test.js.snap
- src/client/components/list/element/ListElement.js
- src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap
- src/client/redux/list.reducer.js
- src/client/utils/requestLists.js
> list bug fixes

- src/client/components/hoc/List/withListCreator.hoc.js
- src/client/utils/requestLists.js
Løser issue: CF-1266 & CF-1267
> Tilføj til ny liste fix

- src/client/components/list/card/ListCard.component.js
- src/client/utils/requestLists.js
- src/server/internal-v1-test.js
- src/server/objectStore.js
- tools/migrate-to-openplatform.js
og også tilføjet  et script til at migrere data
> use scan for fetching private objects

- src/client/components/base/Belt/RecentListsBelt.container.js
- src/client/components/base/T/T.json
- src/client/components/list/card/ListCard.component.js
- src/client/utils/requestLists.js
removes profile image/name and comment counts from listcard
> this is a temporary fix

- src/acceptance/admin_no-db.js
- src/acceptance/admin_test.js
- src/lib/services/searcher.js
- src/lib/services/suggester.js
- src/server/config.js
- src/server/external-server.js
> CF-1246 Suggester Url change + status endpoint

- src/client/components/comments/CommentWrapper.component.js
> CF-1189 comment edit button mobileview

- src/client/components/hero/templates/InteractionSlide.css
> CF-1256 hero tags size fixed

- src/client/components/general/BookmarkButton/BookmarkButton.css
- src/client/components/general/BookmarkButton/BookmarkButton.js
- src/client/components/list/element/ListElement.js
- src/client/components/work/WorkCard/WorkCard.container.js
- src/client/components/work/WorkPage/WorkPage.container.js
- src/client/components/work/WorkPreview/WorkPreview.component.js
> CF-981 changed some bookmark styling

- e2e/cypress/integration/filter.spec.js
- src/client/components/modals/ReorderListModal.container.js
> CF-1278 - ReorderList bug

- e2e/cypress/integration/filter.spec.js
- src/client/components/filter/FilterCards/FilterCards.css
This is a temporary fix - to be solved asap...
This is done to be able to roll out the master
> Re-add overflow hidden on root, and disable filter test

- e2e/cypress/integration/shortList.spec.js
- public/index.html
> CF-1280 Hotjar Script

- e2e/cypress/integration/filter.spec.js
- e2e/cypress/integration/list.spec.js
- package-lock.json
- src/client/components/hoc/Follow/withFollow.hoc.js
Also created a cypress test to test that the follow list button can be turned on and off repeatedly
> Added db generated id to the follow / unfollow routine

- e2e/cypress/integration/list.spec.js
- src/client/components/list/element/ListElement.css
- src/client/components/list/element/ListElement.js
- src/client/components/list/templates/simple/SimpleList.js
- src/client/redux/__tests__/__snapshots__/list.reducer.test.js.snap
- src/client/redux/__tests__/list.reducer.test.js
- src/client/redux/list.reducer.js
Ejer af element i en liste skal vises når elementet kommer fra en anden end ejeren af listen
> fix bug where element owner is not shown

- e2e/cypress/integration/filter.spec.js
- src/client/matomo.js
- src/client/redux/matomo.middleware.js
- src/client/utils/config.js
> CF-838 Matmo - part 1/2

- tools/put-data.js
Tjekket bliver mere specifikt, så vi kun tjekker om database er OK, når vi injecter
> inject data as long as db is up

- public/index.html
i forbindelse med issue CF-1098
> Google Search Console verification tag

- src/client/components/hoc/Scroll/withIsVisible.hoc.js
- src/client/utils/isBot.js
Disable visibility sensor on bot visits
> Disable visibility sensor on bot visits

- public/index.html
læsekompas => laesekompas warning fix (try)
> changed page title

- e2e/cypress/integration/search.spec.js
- src/client/components/filter/FilterPage/Results.component.js
- src/client/components/filter/SearchBar/SearchBar.component.js
- src/client/components/filter/SearchBar/TagsSuggester.component.js
- src/client/components/hoc/AdressBar/withTagsFromUrl.hoc.js
Multi-title suggestions show each matched title with only one tag to represent them. Cypress test created for testing these multi-titles.
> combining matching titles to replace suggestions in state.

- public/index.html
- sitemap.xml
- src/client/App.js
- src/client/components/article/Article.component.js
- src/client/components/base/Belt/RecentListsBelt.container.js
- src/client/components/base/Head/Head.js
- src/client/components/base/Head/index.js
- src/client/components/base/Header/Header.js
- src/client/components/base/Header/index.js
- src/client/components/base/Title/Title.css
- src/client/components/filter/FilterPage/FilterPage.container.js
- src/client/components/frontpage/FrontPage.container.js
- src/client/components/general/BookmarkButton/BookmarkButton.js
- src/client/components/list/ListPage.js
- src/client/components/list/element/ListElement.js
- src/client/components/list/shortlist/ShortList.container.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/profile/EditProfilePage.js
- src/client/components/profile/__tests__/__snapshots__/CreateProfile.test.js.snap
- src/client/components/work/WorkCard/WorkCard.container.js
- src/client/components/work/WorkPage/WorkPage.container.js
- src/client/redux/article.reducer.js
- src/server/external-meta-work.js
- src/server/external-v1-books.js
> CF-1098 bot visibility

- public/sitemap.xml
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/filter/FilterPage/FilterPage.container.js
- src/client/components/list/shortlist/ShortList.container.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/redux/article.reducer.js
- src/client/redux/belts.reducer.js
updated belts + updated meta descriptions + moved sitemap.xml
> uge 28 bånd + små ændringer

- e2e/cypress/integration/head.spec.js
- src/client/components/article/Article.component.js
- src/client/components/base/Head/Head.js
- src/client/components/list/ListPage.js
- src/client/components/list/shortlist/ShortList.container.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/profile/__tests__/__snapshots__/CreateProfile.test.js.snap
- src/client/redux/article.reducer.js
> Head - metadata cypress test

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/list/shortlist/ShortListDropDown.container.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortListDropDown.component.test.js.snap
...to the 2 buttons and link on huskedropdown list so that they toggle off when the huskelist is empty
> added disabled attribute 

- e2e/cypress/integration/head.spec.js
- package-lock.json
- package.json
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/redux/belts.reducer.js
updated frontapge belt + updated lodash version and cypress head test
> forsideindhold uge 29 + det løse

- docker/env.docker
- src/client/components/base/Belt/ListsBelt.container.js
- src/client/components/base/Head/Head.js
- src/client/components/frontpage/FrontPage.container.js
- src/client/components/hoc/Aggregation/index.js
- src/client/components/hoc/Aggregation/withListAggregation.hoc.js
- src/client/components/list/card/ListCard.component.js
- src/client/utils/requester.js
> List-aggregation hoc - based on /aggregation dummy-data

- src/client/redux/shortlist.reducer.js
ryd listen now only clears list and not the entire page.
> fix to CF-1311

- e2e/cypress/integration/filter.spec.js
- src/server/utils/over13.js
> over13() funktionen skal inkludere 13år

- package-lock.json
- public/index.html
- src/client/components/base/ContextMenu/ContextMenu.css
- src/client/components/base/ContextMenu/ContextMenu.js
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/components/frontpage/FrontPage.container.js
- src/client/components/general/AddToListButton/AddToListButton.component.js
- src/client/components/general/AddToListButton/AddToListButton.css
- src/client/components/list/shortlist/__tests__/ShortList.container.test.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/modals/Modal/Modal.component.js
- src/client/components/work/WorkPage/WorkPage.container.js
- src/client/components/work/WorkPreview/WorkPreview.component.js
- src/client/components/work/WorkPreview/WorkPreview.css
- src/client/components/work/workFunctions.js
- src/client/utils/isInViewport.js
- src/client/utils/scrollDirection.js
- src/server/external-v1-books.js
> Cf 1249 remove js dependencies

- src/client/components/base/T/T.json
- src/client/components/top/TopBar.component.js
- src/client/components/work/WorkPage/WorkPage.container.js
- src/server/external-v1-books.js
> Opdatering af beta-modal tekst

- src/client/components/hoc/Recommender/withInteractionsToPids.hoc.js
- src/client/redux/interaction.reducer.js
løser issue: CF-1319 og CF-1174
> Medregn først nye interactioner ved refresh

- src/client/components/modals/Modal/Modal.css
- src/client/components/modals/ReorderListModal.container.js
> Sorter-liste fix

- package-lock.json
- src/client/components/base/Belt/TagsBelt.component.js
- src/client/components/frontpage/FrontPage.container.js
- src/client/matomo.js
- src/server/internal-v1-test.js
> stylefix - belt

- src/client/components/work/WorkPage/WorkPage.container.js
- src/client/components/work/WorkPage/WorkPage.css
> workpage style fix

- package-lock.json
- src/client/components/base/T/T.json
- src/client/components/work/WorkPage/WorkPage.container.js
changed names of toggle button names when showing/hiding tags
> shows priority tags if they exist. 

- package-lock.json
- src/client/components/article/pages/loginError.md
- src/client/components/base/Belt/MultiRowContainer.js
- src/client/redux/article.reducer.js
- src/server/external-v1-auth.js
- src/setupTests.js
> CF-1209 login-error page

- package-lock.json
- src/client/components/base/Belt/similarBelt.css
- src/client/components/belteditor/CreateBelt.component.js
- src/client/components/work/WorkCard/WorkCard.container.js
- src/client/components/work/WorkCard/WorkCard.css
- src/server/internal-v1-test.js
løser issue: CF-1288
https://dbcjira.atlassian.net/secure/RapidBoard.jspa?rapidView=71&projectKey=FE2&modal=detail&selectedIssue=CF-1288
> CF-1288: Hoverfix on workCard

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/redux/belts.reducer.js
> Forsidebånd uge 37

- src/client/components/belteditor/CreateBelt.component.js
- src/client/redux/belts.reducer.js
- src/server/external-v1-initial-state.js
- src/shared/belts.requester.js
løser issue: CF-1357
https://dbcjira.atlassian.net/browse/CF-1357
> CF-1357 pin fix

- src/client/components/base/Belt/WorkSlider.component.js
- src/client/components/base/Belt/similarBelt.css
- src/client/components/work/CompareBooks/CompareBooks.component.js
- src/client/components/work/CompareBooks/CompareBooks.css
- src/client/components/work/WorkCard/WorkCard.container.js
- src/client/components/work/WorkCard/WorkCard.css
løser issue: CF-1353
https://dbcjira.atlassian.net/browse/CF-1353
> CF-1353 compare mobile update

- src/client/components/base/Belt/SimilarBelt.component.js
- src/client/components/base/Belt/WorkSlider.component.js
- src/client/components/work/WorkCard/WorkCard.container.js
> WorkCard onClick mobile bug

- e2e/cypress/integration/list.spec.js
- src/client/components/comments/CommentInput.component.js
- src/client/components/comments/__tests__/__snapshots__/CommentContainer.test.js.snap
- src/client/components/comments/__tests__/__snapshots__/CommentWrapper.test.js.snap
- src/client/components/list/element/ListElement.js
- src/client/components/list/templates/bookcase/BookcaseList.js
- src/client/components/list/templates/simple/SimpleList.js
Fixer rediger liste-element-beskrivelse
https://dbcjira.atlassian.net/browse/CF-1376
> added test, fixed bug

- e2e/cypress/fixtures/order/canorderawork.mock.json
- e2e/cypress/fixtures/order/orderbuttondisabledwhileloadingavailability.mock.json
- e2e/cypress/fixtures/order/orderbuttondisabledwhileloadinguser.mock.json
- src/client/components/work/workFunctions.js
- src/client/redux/order.middleware.js
Revert story and wait for multivolume handling
> Filter pids in collection to same type as the actual pid

- e2e/cypress/integration/list.spec.js
- src/shared/list.requester.js
Henter op til 1000 lister ud
Sletter systemlister som er dubletter
> Cf 1385 increase list limit

- src/client/components/base/Belt/Slider.component.js
Also removed the end arrow when it was appearing for no reason or without purpose.
> reworked slider to encompass all components that use it.

- e2e/cypress/integration/filter.spec.js
- src/client/components/filter/SearchBar/TagsSuggester.component.js
løser issue: CF-1380
https://dbcjira.atlassian.net/secure/RapidBoard.jspa?rapidView=71&projectKey=FE2&modal=detail&selectedIssue=CF-1380
> CF-1380 - Filterpage: Removed .blur() on desktop enter click

- e2e/cypress/fixtures/kiosk/initialStateKioskEnabled.json
- e2e/cypress/fixtures/kiosk/initialStateKioskEnabledWithClientId.json
- e2e/cypress/fixtures/kiosk/kioskConfiguration.json
- e2e/cypress/integration/kiosk.spec.js
- src/client/App.js
- src/client/components/base/Kiosk/Kiosk.js
- src/client/components/base/T/T.json
- src/client/components/base/Text/Text.css
- src/client/components/kiosk/KioskSetup.component.js
- src/client/components/kiosk/KioskSetup.css
- src/client/components/top/TopBar.component.js
- src/client/redux/kiosk.reducer.js
- src/client/redux/kiosk.thunk.js
- src/client/redux/root.reducer.js
- src/client/utils/localstorage.js
- src/server/config.js
- src/server/external-v1-initial-state.js
- src/server/external-v1-kiosk.js
- src/server/external-v1.js
- src/server/smaug.js
- Man aktiverer kiosk-mode med miljøvariabel: KIOSK_ENABLED=true
- Herefter redirectes til kiosk-opsætning, hvor man kan indtaste clientId+secret. Hver gang siden loades hentes configuration ud af smaug - hvis id/secret ikke er gyldig så redirectes man til kiosk-opsætning.
- Som eksempel på brug af kiosk-komponenten er login-knappen skjult
> added kiosk config page, and a base kiosk component

- e2e/cypress/integration/head.spec.js
- e2e/cypress/integration/kiosk.spec.js
- public/index.html
- src/client/App.js
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/T/T.json
- src/client/components/filter/FilterCards/FilterCards.css
- src/client/components/filter/FilterCards/templates/CardList.css
- src/client/components/filter/FilterCards/templates/CardRange.css
- src/client/components/filter/FilterPage/FilterPage.container.js
- src/client/components/filter/FilterPage/FilterPage.css
- src/client/components/filter/SearchBar/SearchBar.css
- src/client/components/kiosk/Navigation/Navigation.component.js
- src/client/components/kiosk/Navigation/Navigation.css
løser issue: CF-1393
https://dbcjira.atlassian.net/secure/RapidBoard.jspa?rapidView=71&modal=detail&selectedIssue=CF-1393
> CF-1393 kiosk navigation

- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/general/BookCover/BookCover.component.js
- src/client/components/general/Footer/Footer.component.js
- src/client/components/kiosk/Navigation/Navigation.component.js
- src/client/components/top/TopBar.component.js
The infomedia logo was already there - no change.
Fixed warnings by adding alt attributes to imgs and aria to object
> Infomedia logo

- e2e/cypress/integration/filter.spec.js
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/top/TopBar.component.js
Løser issue: CF-1422
https://dbcjira.atlassian.net/browse/CF-1422
> Bug: CF-1422 logo på søgeside

- src/client/App.js
- src/client/components/frontpage/FrontPage.container.js
- src/client/components/hero/Hero.css
- src/client/components/kiosk/KioskHero.component.js
- src/client/components/kiosk/KioskHero.css
løser issue CF-1392
https://dbcjira.atlassian.net/secure/RapidBoard.jspa?rapidView=71&projectKey=FE2&modal=detail&selectedIssue=CF-1392
> CF-1392-remove-some-general-components

- src/client/components/base/T/T.json
- src/client/components/modals/OrderModal.container.js
- src/client/components/work/CompareBooks/CompareBooks.css
> 1425 noclick tags textfix stvi

- src/client/App.js
- src/client/components/kiosk/Navigation/Navigation.component.js
- src/client/components/kiosk/Navigation/Navigation.css
- src/client/components/kiosk/Timeout/Timeout.js
- src/client/redux/router.reducer.js
løser issue: CF-1396
https://dbcjira.atlassian.net/browse/CF-1396
> CF-1396 - Timeout

- src/client/redux/holdings.reducer.js
- src/client/redux/holdings.thunk.js
Reducer antallet af HTTP requests ved brug af lodash throttle
> holdings performance optimizations

- e2e/cypress/fixtures/recompass/simple.json
- e2e/cypress/integration/kiosk.spec.js
- e2e/cypress/support/commands.js
- src/client/components/base/Belt/MultiRowContainer.js
- src/client/components/general/CompareButton/CompareButton.component.js
- src/client/components/kiosk/WorkPage/KioskWorkPage.component.js
- src/client/components/work/WorkCard/WorkCard.container.js
og lidt reorganisering af kiosk cypress tests
> make bookcompare available in kiosk mode

- src/client/components/hoc/List/withList.hoc.js
- src/client/components/work/Appeals/Appeals.component.js
This PR includes 2 bug fixes: 
CF-1424 - making it possible to print lists 
CF-1439 - making the tag buttons in læseoplevelse work when in preview state
> Bugs noprint inactivebts stvi

- src/client/components/comments/CommentCounter.component.js
- src/client/components/filter/FilterCards/FilterCards.css
- src/client/components/list/templates/bookcase/BookcaseList.js
- src/client/components/list/templates/bookcase/ListInfo.js
- src/client/components/list/templates/simple/ListInfo.js
- src/client/components/list/templates/simple/SimpleList.js
- src/client/components/work/WorkCard/WorkCard.css
- src/client/components/work/WorkPreview/WorkPreview.css
This merge fixes bugs related to issues CF-1225 (linear-gradient) and CF-1426(scroll to list comments).
> Bugs various stvi

- src/client/components/base/Belt/Slider.component.js
- src/client/components/base/Belt/Slider.css
- src/client/components/work/WorkCard/WorkCard.container.js
- src/client/components/work/WorkCard/WorkCard.css
> kiosk belt performance

- src/client/components/hoc/Belt/withChildBelt.hoc.js
- src/client/components/work/WorkPage/WorkPage.container.js
- src/client/components/work/WorkPreview/WorkPreview.component.js
NB. this also fixes workpage minderom so that it no longer creates 2 minderom belts
> mobile minderom button goes to minderom belt

- src/client/components/hoc/Permissions/permissions.json
- src/client/components/modals/CompareBooksModal.component.js
- src/client/components/work/CompareBooks/CompareBooks.css
- src/client/components/work/WorkPage/WorkPage.css
- Fjerner hvid top på værkside
- Redaktør skal ikke kunne se sammenlign
- Sammenlign modal skal kunne gå i overflow
- Coverbilleder skal bevare størrelser i mobil
> small fixes

- src/client/components/hoc/Permissions/permissions.json
- src/client/components/hoc/Permissions/withPermissions.hoc.js
- src/client/components/list/button/PrintButton.js
løser issue CF-1269 
https://dbcjira.atlassian.net/browse/CF-1469
> CF-1469 Print as pro-func

- public/index.html
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/Head/Head.js
- src/client/components/list/shortlist/__tests__/ShortList.container.test.js
- src/client/components/list/shortlist/__tests__/__snapshots__/ShortList.container.test.js.snap
- src/client/components/profile/__tests__/__snapshots__/CreateProfile.test.js.snap
- src/setupTests.js
> Kiosk hotjar

- src/client/components/modals/ProfileModal/ProfileModal.component.js
> Age modal centered

- docker/env.docker
- src/client/components/hoc/Recommender/withPidsToPids.hoc.js
- src/client/redux/recommend.thunk.js
- src/lib/services/recompas-tags.js
- src/server/external-v1-recompass.js
Reverts DBCDK/content-first#1256
> Revert "add timeout to recompass requests. show skeleton on 'minder om' result"

- e2e/cypress/integration/login.spec.js
> cypress AP login test fixed

- docker-compose-cypress.yml
- e2e/cypress/integration/filter.spec.js
- e2e/cypress/integration/search.spec.js
- src/client/App.js
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/base/Belt/BeltSkeleton.component.js
- src/client/components/base/Belt/BeltSkeleton.css
- src/client/components/base/Belt/PersonalBelt.component.js
- src/client/components/base/Belt/TagsBelt.component.js
- src/client/components/base/Kiosk/Kiosk.js
- src/client/components/base/Skeleton/Card/Card.js
- src/client/components/filter/SearchBar/TagsSuggester.component.js
- src/client/redux/belts.reducer.js
- src/client/redux/kiosk.reducer.js
- src/client/redux/recommend.thunk.js
- src/client/redux/root.reducer.js
- src/client/utils/config.js
- src/client/utils/loadInitialState.js
- src/index.js
- src/server/external-server.js
> handling initial state loading errors

- src/client/components/top/Topbar.css
> searchbar on ipad made visible

- src/server/external-meta-work.js
> CF-1514 fixed facebook share bug

- src/client/components/hoc/Follow/withFollow.hoc.js
- src/client/components/hoc/Follow/withFollows.hoc.js
- src/client/redux/follow.reducer.js
Man skal ikke lave requestet før brugeren er logget ind. Og request på alle follows skal ikke forhindres af et request på et enkelt follow.
> fix follows bug

- src/server/external-meta-work.js
> fixed external-meta-work bug

- e2e/cypress/fixtures/kiosk/initialStateKioskEnabledWithClientId.json
- e2e/cypress/integration/homeStatus.spec.js
- e2e/cypress/integration/matomo.spec.js
- e2e/cypress/support/commands.js
- src/client/matomo.js
- src/client/redux/matomo.middleware.js
- src/lib/services/holdings.js
- src/lib/services/recompas-tags.js
> set branch key as a custom matomo vriable when running in kiosk mode

- docker/env.docker
- src/client/components/hoc/Recommender/withPidsToPids.hoc.js
- src/client/redux/recommend.thunk.js
- src/server/external-v1-recompass.js
AFVENTER - må først merges når vi kan bruge recompass 1.2 på prod
> Recompass timing threshold

- e2e/cypress/integration/order.spec.js
- src/client/components/base/T/T.json
- src/client/components/filter/SearchBar/SearchBar.component.js
- src/client/components/general/CompareButton/CompareButton.component.js
- src/client/components/hoc/Permissions/context.js
- src/client/components/hoc/Permissions/withPermissions.hoc.js
- src/client/components/list/button/PrintButton.js
- src/client/components/modals/ConfirmModal.component.js
> updated modal content

- src/client/components/top/Topbar.css
> fixed ipad search bar issue

- src/lib/services/holdings.js
- src/lib/services/idmapper.js
- src/lib/services/matomo.js
- src/lib/services/recompas-tags.js
- src/lib/services/recompas-work.js
- src/lib/services/searcher.js
- src/lib/services/smaug/authentication-smaug.js
- src/lib/services/suggester.js
- src/server/external-server.js
- src/server/external-v1-kiosk.js
- src/server/external-v1-libraries.js
- src/server/external-v1-log.js
- src/server/external-v1-openplatform.js
- src/server/external-v1-shortlist.js
- src/server/internal-server.js
- src/server/passport.js
- src/server/user.js
Had problems with merging master into 262-logfile-stvi . This is a new clean version.
> 262 logfile update stvi

- docker-compose-cypress.yml
- e2e/cypress/integration/belt.spec.js
- e2e/cypress/integration/filter.spec.js
- e2e/cypress/integration/list.spec.js
- e2e/cypress/integration/login.spec.js
- e2e/cypress/integration/logout.spec.js
- e2e/cypress/integration/matomo.spec.js
- e2e/cypress/integration/search.spec.js
- e2e/cypress/plugins/index.js
- e2e/cypress/support/commands.js
- package-lock.json
- src/client/components/general/BookCover/BookCover.css
- src/client/components/general/CookieWarning/CookieWarning.js
- tools/put-data.js
Forsøg på at løse issue CF-1554
https://dbcjira.atlassian.net/secure/RapidBoard.jspa?rapidView=71&projectKey=FE2&modal=detail&selectedIssue=CF-1554
> Stabilisere Cypress test

- src/client/components/work/WorkPreview/WorkPreview.css
> work view width fixed

- Jenkinsfile
- docker-compose-cypress.yml
- docker/env.docker
- src/server/external-v1-books.js
> fixed search results bug

- e2e/cypress/integration/filter.spec.js
- e2e/cypress/integration/work.spec.js
- e2e/cypress/support/commands.js
- src/client/components/base/T/T.json
- src/server/external-v1-series.js
Solves issues in [CF-1252]
[CF-1252]: https://dbcjira.atlassian.net/browse/CF-1252
> remove mangaprint editions from series endpoint

- e2e/cypress/integration/belt.spec.js
- e2e/cypress/integration/beltEditor.spec.js
- e2e/cypress/integration/beltForm.spec.js
- e2e/cypress/integration/head.spec.js
- e2e/cypress/integration/list.spec.js
- e2e/cypress/integration/login.spec.js
- e2e/cypress/integration/matomo.spec.js
- e2e/cypress/integration/notice.spec.js
- e2e/cypress/integration/order.spec.js
- e2e/cypress/integration/permissions.spec.js
- e2e/cypress/integration/shortList.spec.js
- e2e/cypress/support/commands.js
- e2e/cypress/support/index.js
- src/client/App.js
- src/client/__tests__/__snapshots__/App.test.js.snap
- src/client/components/modals/Modal/Modal.css
- src/client/components/modals/ReorderListModal.css
- src/client/components/notice/Notice.component.js
Part of [CF-1577]
[CF-1577]: https://dbcjira.atlassian.net/browse/CF-1577
> Get ready to open for orders

- e2e/cypress/support/commands.js
- src/server/internal-v1-test.js
> Add logging to create test user

- src/client/components/modals/ProfileModal/ProfileModal.component.js
- src/client/components/modals/ProfileModal/ProfileModal.css
- src/client/components/profile/ProfileUpdateUser.component.js
- src/server/external-v1-books.js
- src/server/utils/over13.js
> show acceptAge checkbox when user age is unknown

- src/server/config.js
> updated SOLR url

- src/client/components/base/T/T.json
- src/client/components/work/Review/FullTextReview.component.js
- src/client/components/work/Review/Review.css
- src/client/components/work/Review/__tests__/__snapshots__/FullTextReview.component.test.js.snap
> fixed bugs in review modal

- src/client/components/work/Review/FullTextReview.component.js
> fixed comma before author name bug in paper review modal

- src/client/components/list/overview/ListOverviewDropDown.container.js
> fixed list modal animation

- src/server/external-v1-books.js
> show genre and form

- src/client/utils/booksTaxonomy.js
- src/server/external-v1-books.js
based on category to which they are associated
> titles with the same name but unique ids are chosen from taxonomy

- src/client/App.js
> removed closed library pop up

- src/server/external-server.js
> monitor kiosk services
